cmake_minimum_required(VERSION 3.31)

add_library(mdr_PlatformMacOS PlatformMacOS.mm)

find_library(IOBLUETOOTH_FRAMEWORK IOBluetooth REQUIRED)
find_library(FOUNDATION_FRAMEWORK Foundation REQUIRED)

target_link_libraries(mdr_PlatformMacOS PRIVATE mdr-c mdr ${IOBLUETOOTH_FRAMEWORK} ${FOUNDATION_FRAMEWORK})

set(MDR_PLATFORM_SHARED_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/PlatformMacOS.mm" PARENT_SCOPE)
set(MDR_PLATFORM_SHARED_LIBS ${IOBLUETOOTH_FRAMEWORK} ${FOUNDATION_FRAMEWORK} PARENT_SCOPE)
