#pragma once
#include <cstdint>
#include "Protocol.hpp"
namespace mdr::v2
{
struct MessageMdrV2EnableDisable
{
	enum Value : UInt8
	{
		ENABLE = 0,
		DISABLE = 1
	} value;

	constexpr MessageMdrV2EnableDisable(Value v) : value(v) {}
	constexpr MessageMdrV2EnableDisable(bool v) : value(v ? ENABLE : DISABLE) {}

    constexpr operator bool() const noexcept { return value == ENABLE; }
    const bool IsValid() const noexcept { return value == ENABLE || value == DISABLE; }
};

struct MessageMdrV2OnOffSettingValue
{
	enum Value : UInt8
	{
		ON = 0,
		OFF = 1
	} value;

	constexpr MessageMdrV2OnOffSettingValue(Value v) : value(v) {}
	constexpr MessageMdrV2OnOffSettingValue(bool v) : value(v ? ON : OFF) {}

	constexpr operator bool() const noexcept { return value == ON; }
    const bool IsValid() const noexcept { return value == ON || value == OFF; }
};

// CONNECT_*_SUPPORT_FUNCTION
// Extracted from Sound Connect iOS 12.2.0

enum class MessageMdrV2FunctionType_Table1 : UInt8
{
	CONCIERGE_DATA = 0x10,
	CONNECTION_STATUS = 0x11,
	CODEC_INDICATOR = 0x12,
	UPSCALING_INDICATOR = 0x13,
	BLE_SETUP = 0x14,
	TUTORIAL_CONTENTS_SELECT_ON_CONCIERGE = 0x15,
	CONNECTION_ESTABLISHED_TIME = 0x16,
	UNNECESSARY_AUTO_RECONNECTION = 0x17,
	DEVICE_SPECIAL_MODE = 0x18,
	PHONE_AND_CONNECTED_DEVICE_INFOMATION_FOR_CLASSIC = 0x19,
	TANDEM_RECONNECTION_REQUEST = 0x1A,
	DISPLAY_FW_VERSION = 0x1B,
	BATTERY_LEVEL_INDICATOR = 0x20,
	LEFT_RIGHT_BATTERY_LEVEL_INDICATOR = 0x21,
	CRADLE_BATTERY_LEVEL_INDICATOR = 0x22,
	POWER_OFF = 0x23,
	AUTO_POWER_OFF = 0x24,
	AUTO_POWER_OFF_WITH_WEARING_DETECTION = 0x25,
	POWER_SAVING_MODE_ON_OFF = 0x26,
	TANDEM_KEEP_ALIVE = 0x27,
	BATTERY_LEVEL_WITH_THRESHOLD = 0x28,
	LR_BATTERY_LEVEL_WITH_THRESHOLD = 0x29,
	CRADLE_BATTERY_LEVEL_WITH_THRESHOLD = 0x2A,
	BATTERY_SAFE_MODE = 0x2B,
	CARING_CHARGE = 0x2C,
	BT_STANDBY = 0x2D,
	STAMINA = 0x2E,
	AUTOMATIC_TOUCH_PANEL_BACKLIGHT_TURN_OFF = 0x2F,
	FW_UPDATE_MTK_TRANSFER_WITHOUT_DISCONNECTION = 0x32,
	FW_UPDATE_MTK_TRANSFER_WITHOUT_DISCONNECTION_AUTO_UPDATE = 0x34,
	FW_UPDATE_MTK_TRANSFER_WITH_REPAIR_MODE = 0x35,
	FW_UPDATE_MTK_TRANSFER_WITH_AC_CONNECTION_CHECK = 0x36,
	FW_UPDATE_TANDEM_TRANSFER_USING_COMMON_TABLE = 0x37,
	FW_UPDATE_USING_MC_APP = 0x38,
	TWS_SUPPORTS_A2DP_LEA_UNI_LEA_BROAD_WITH_CTKD = 0x40,
	HBS_SUPPORTS_A2DP_LEA_UNI_LEA_BROAD_WITH_CTKD = 0x41,
	CLASSIC_ONLY_LE_CLASSIC_SETTING = 0x42,
	TWS_SUPPORTS_LEA_UNI_LEA_BROAD = 0x43,
	CHANGE_TANDEM_CONNECTION_PROFILE_FOR_ANDROID = 0x44,
	BGM_MODE_CANT_BE_USED_WITH_LEA_CONNECTION = 0x45,
	HEAD_TRACKER_CANT_BE_USED_WITH_LEA_CONNECTION = 0x46,
	PAIRING_DEVICE_MANAGEMENT_CANT_BE_USED_WITH_LEA_CONNECTION = 0x47,
	SOUND_AR_CANT_BE_USED_WITH_LEA_CONNECTION = 0x48,
	AUTO_PLAY_CANT_BE_USED_WITH_LEA_CONNECTION = 0x49,
	GATT_CONNECTABLE_CANT_BE_USED_WITH_LEA_CONNECTION = 0x4A,
	SOUND_AR_OPTIMIZATION_CANT_BE_USED_WITH_LEA_CONNECTION = 0x4B,
	QUICK_ACCESS_CANT_BE_USED_WITH_LEA_CONNECTION = 0x4C,
	CONNECTION_MODE_CANT_BE_USED_WITH_LEA_CONNECTION = 0x4D,
	VOICE_ASSISTANT_SETTINGS_CANT_BE_USED_WITH_LEA_CONNECTION = 0x4E,
	VOICE_ASSISTANT_WAKE_WORD_CANT_BE_USED_WITH_LEA_CONNECTION = 0x4F,
	PRESET_EQ = 0x50,
	EBB = 0x51,
	PRESET_EQ_NON_CUSTOMIZABLE = 0x52,
	PRESET_EQ_AND_ULT_MODE = 0x53,
	SOUND_EFFECT = 0x54,
	CUSTOM_EQ = 0x55,
	TURN_KEY_EQ = 0x56,
	PRESET_EQ_AND_ERRORCODE = 0x57,
	NOISE_CANCELLING_ONOFF = 0x61,
	NOISE_CANCELLING_ONOFF_AND_AMBIENT_SOUND_MODE_ONOFF = 0x62,
	NOISE_CANCELLING_DUAL_SINGLE_OFF_AND_AMBIENT_SOUND_MODE_ONOFF = 0x63,
	NOISE_CANCELLING_ONOFF_AND_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT = 0x64,
	NOISE_CANCELLING_DUAL_SINGLE_OFF_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT = 0x65,
	AMBIENT_SOUND_MODE_ONOFF = 0x66,
	AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT = 0x67,
	MODE_NC_ASM_NOISE_CANCELLING_DUAL_AUTO_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT = 0x68,
	AMBIENT_SOUND_CONTROL_MODE_SELECT = 0x69,
	MODE_NC_ASM_NOISE_CANCELLING_DUAL_SINGLE_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT = 0x6A,
	MODE_NC_ASM_NOISE_CANCELLING_DUAL_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT = 0x6B,
	MODE_NC_NCSS_ASM_NOISE_CANCELLING_DUAL_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT_WITH_TEST_MODE = 0x6C,
	MODE_NC_ASM_NOISE_CANCELLING_DUAL_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT_NOISE_ADAPTATION = 0x6D,
	AUTO_NCASM = 0x70,
	ADAPTIVE_CONTROL_WITH_PARAMETER_NOTIFICATION = 0x71,
	NC_OPTIMIZER_PERSONAL_BAROMETRIC = 0x80,
	NC_OPTIMIZER_PERSONAL = 0x81,
	NC_OPTIMIZER_BAROMETRIC = 0x82,
	SOUND_FIELD_OPTIMIZATION = 0x83,
	TV_SOUND_BOOSTER = 0x84,
	FIXED_MESSAGE = 0x90,
	VIBRATOR_ALERT_NOTIFICATION = 0x91,
	FIXED_MESSAGE_WITH_LR_SELECTION = 0x92,
	VOICE_ASSISTANT_ALERT_NOTIFICATION = 0x93,
	LE_AUDIO_ALERT_NOTIFICATION = 0x94,
	PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT = 0xA1,
	PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT_AND_MUTE = 0xA2,
	PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT_AND_FUNCTION_CHANGE = 0xA3,
	PLAYBACK_CONTROLLER_WITH_FUNCTION_CHANGE = 0xA4,
	SAR = 0xB0,
	AUTO_PLAY = 0xB1,
	GATT_CONNECTABLE = 0xB2,
	SAR_OPTIMIZATION_COMPASS_ACCEL_TYPE = 0xB3,
	HEAD_TRACKER_COMPASS_ACCEL_TYPE = 0xB5,
	SAR_OPTIMIZATION_ACCEL_TYPE = 0xB6,
	HEAD_TRACKER_ACCEL_TYPE = 0xB7,
	INTEGRATED_AUTO_PLAY = 0xB8,
	ACTION_LOG_NOTIFIER = 0xC1,
	TIME_SERIES_OPERATIONLOG_NOTIFIER = 0xC2,
	SOUND_DROPOUT_NOTIFIER = 0xC3,
	GENERAL_SETTING_1 = 0xD1,
	GENERAL_SETTING_2 = 0xD2,
	GENERAL_SETTING_3 = 0xD3,
	GENERAL_SETTING_4 = 0xD4,
	CONNECTION_MODE_SOUND_QUALITY_CONNECTION_QUALITY = 0xE1,
	UPSCALING_AUTO_OFF = 0xE2,
	CONNECTION_MODE_SOUND_QUALITY_SOUND_WITH_LDAC_STATUS_QUALITY_CONNECTION_QUALITY = 0xE3,
	BGM_MODE_SMALL_MIDDLE_LARGE = 0xE4,
	UPMIX_CINEMA = 0xE5,
	LISTENING_OPTION = 0xE6,
	CONNECTION_MODE_CLASSIC_AUDIO_LE_AUDIO = 0xE7,
	VOICE_CONTENTS = 0xE8,
	SOUND_LEAKAGE_REDUCTION = 0xE9,
	LISTENING_OPTION_ASSIGN_CUSTOMIZABLE = 0xEA,
	BGM_MODE_SMALL_MIDDLE_LARGE_AND_ERRORCODE = 0xEB,
	UPMIX_SERIES = 0xEC,
	VIBRATOR_ON_OFF = 0xF0,
	PLAYBACK_CONTROL_BY_WEARING_REMOVING_HEADPHONE_ON_OFF = 0xF1,
	SMART_TALKING_MODE_TYPE1 = 0xF2,
	ASSIGNABLE_SETTING = 0xF3,
	VOICE_ASSISTANT_SETTINGS = 0xF4,
	VOICE_ASSISTANT_WAKE_WORD_ON_OFF = 0xF5,
	WEARING_STATUS_DETECTOR = 0xF6,
	EARPIECE_SELECTION = 0xF7,
	CALL_SETTINGS = 0xF8,
	RESET_SETTINGS = 0xF9,
	AUTO_VOLUME = 0xFA,
	FACE_TAP_TEST_MODE = 0xFB,
	SMART_TALKING_MODE_TYPE2 = 0xFC,
	QUICK_ACCESS = 0xFD,
	ASSIGNABLE_SETTING_WITH_LIMITATION = 0xFE,
	HEAD_GESTURE_ON_OFF_TRAINING = 0xFF,
};

inline const char* format_as(MessageMdrV2FunctionType_Table1 func)
{
	switch (func)
	{
	case MessageMdrV2FunctionType_Table1::CONCIERGE_DATA: return "CONCIERGE_DATA";
	case MessageMdrV2FunctionType_Table1::CONNECTION_STATUS: return "CONNECTION_STATUS";
	case MessageMdrV2FunctionType_Table1::CODEC_INDICATOR: return "CODEC_INDICATOR";
	case MessageMdrV2FunctionType_Table1::UPSCALING_INDICATOR: return "UPSCALING_INDICATOR";
	case MessageMdrV2FunctionType_Table1::BLE_SETUP: return "BLE_SETUP";
	case MessageMdrV2FunctionType_Table1::TUTORIAL_CONTENTS_SELECT_ON_CONCIERGE: return "TUTORIAL_CONTENTS_SELECT_ON_CONCIERGE";
	case MessageMdrV2FunctionType_Table1::CONNECTION_ESTABLISHED_TIME: return "CONNECTION_ESTABLISHED_TIME";
	case MessageMdrV2FunctionType_Table1::UNNECESSARY_AUTO_RECONNECTION: return "UNNECESSARY_AUTO_RECONNECTION";
	case MessageMdrV2FunctionType_Table1::DEVICE_SPECIAL_MODE: return "DEVICE_SPECIAL_MODE";
	case MessageMdrV2FunctionType_Table1::PHONE_AND_CONNECTED_DEVICE_INFOMATION_FOR_CLASSIC: return "PHONE_AND_CONNECTED_DEVICE_INFOMATION_FOR_CLASSIC";
	case MessageMdrV2FunctionType_Table1::TANDEM_RECONNECTION_REQUEST: return "TANDEM_RECONNECTION_REQUEST";
	case MessageMdrV2FunctionType_Table1::DISPLAY_FW_VERSION: return "DISPLAY_FW_VERSION";
	case MessageMdrV2FunctionType_Table1::BATTERY_LEVEL_INDICATOR: return "BATTERY_LEVEL_INDICATOR";
	case MessageMdrV2FunctionType_Table1::LEFT_RIGHT_BATTERY_LEVEL_INDICATOR: return "LEFT_RIGHT_BATTERY_LEVEL_INDICATOR";
	case MessageMdrV2FunctionType_Table1::CRADLE_BATTERY_LEVEL_INDICATOR: return "CRADLE_BATTERY_LEVEL_INDICATOR";
	case MessageMdrV2FunctionType_Table1::POWER_OFF: return "POWER_OFF";
	case MessageMdrV2FunctionType_Table1::AUTO_POWER_OFF: return "AUTO_POWER_OFF";
	case MessageMdrV2FunctionType_Table1::AUTO_POWER_OFF_WITH_WEARING_DETECTION: return "AUTO_POWER_OFF_WITH_WEARING_DETECTION";
	case MessageMdrV2FunctionType_Table1::POWER_SAVING_MODE_ON_OFF: return "POWER_SAVING_MODE_ON_OFF";
	case MessageMdrV2FunctionType_Table1::TANDEM_KEEP_ALIVE: return "TANDEM_KEEP_ALIVE";
	case MessageMdrV2FunctionType_Table1::BATTERY_LEVEL_WITH_THRESHOLD: return "BATTERY_LEVEL_WITH_THRESHOLD";
	case MessageMdrV2FunctionType_Table1::LR_BATTERY_LEVEL_WITH_THRESHOLD: return "LR_BATTERY_LEVEL_WITH_THRESHOLD";
	case MessageMdrV2FunctionType_Table1::CRADLE_BATTERY_LEVEL_WITH_THRESHOLD: return "CRADLE_BATTERY_LEVEL_WITH_THRESHOLD";
	case MessageMdrV2FunctionType_Table1::BATTERY_SAFE_MODE: return "BATTERY_SAFE_MODE";
	case MessageMdrV2FunctionType_Table1::CARING_CHARGE: return "CARING_CHARGE";
	case MessageMdrV2FunctionType_Table1::BT_STANDBY: return "BT_STANDBY";
	case MessageMdrV2FunctionType_Table1::STAMINA: return "STAMINA";
	case MessageMdrV2FunctionType_Table1::AUTOMATIC_TOUCH_PANEL_BACKLIGHT_TURN_OFF: return "AUTOMATIC_TOUCH_PANEL_BACKLIGHT_TURN_OFF";
	case MessageMdrV2FunctionType_Table1::FW_UPDATE_MTK_TRANSFER_WITHOUT_DISCONNECTION: return "FW_UPDATE_MTK_TRANSFER_WITHOUT_DISCONNECTION";
	case MessageMdrV2FunctionType_Table1::FW_UPDATE_MTK_TRANSFER_WITHOUT_DISCONNECTION_AUTO_UPDATE: return "FW_UPDATE_MTK_TRANSFER_WITHOUT_DISCONNECTION_AUTO_UPDATE";
	case MessageMdrV2FunctionType_Table1::FW_UPDATE_MTK_TRANSFER_WITH_REPAIR_MODE: return "FW_UPDATE_MTK_TRANSFER_WITH_REPAIR_MODE";
	case MessageMdrV2FunctionType_Table1::FW_UPDATE_MTK_TRANSFER_WITH_AC_CONNECTION_CHECK: return "FW_UPDATE_MTK_TRANSFER_WITH_AC_CONNECTION_CHECK";
	case MessageMdrV2FunctionType_Table1::FW_UPDATE_TANDEM_TRANSFER_USING_COMMON_TABLE: return "FW_UPDATE_TANDEM_TRANSFER_USING_COMMON_TABLE";
	case MessageMdrV2FunctionType_Table1::FW_UPDATE_USING_MC_APP: return "FW_UPDATE_USING_MC_APP";
	case MessageMdrV2FunctionType_Table1::TWS_SUPPORTS_A2DP_LEA_UNI_LEA_BROAD_WITH_CTKD: return "TWS_SUPPORTS_A2DP_LEA_UNI_LEA_BROAD_WITH_CTKD";
	case MessageMdrV2FunctionType_Table1::HBS_SUPPORTS_A2DP_LEA_UNI_LEA_BROAD_WITH_CTKD: return "HBS_SUPPORTS_A2DP_LEA_UNI_LEA_BROAD_WITH_CTKD";
	case MessageMdrV2FunctionType_Table1::CLASSIC_ONLY_LE_CLASSIC_SETTING: return "CLASSIC_ONLY_LE_CLASSIC_SETTING";
	case MessageMdrV2FunctionType_Table1::TWS_SUPPORTS_LEA_UNI_LEA_BROAD: return "TWS_SUPPORTS_LEA_UNI_LEA_BROAD";
	case MessageMdrV2FunctionType_Table1::CHANGE_TANDEM_CONNECTION_PROFILE_FOR_ANDROID: return "CHANGE_TANDEM_CONNECTION_PROFILE_FOR_ANDROID";
	case MessageMdrV2FunctionType_Table1::BGM_MODE_CANT_BE_USED_WITH_LEA_CONNECTION: return "BGM_MODE_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::HEAD_TRACKER_CANT_BE_USED_WITH_LEA_CONNECTION: return "HEAD_TRACKER_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::PAIRING_DEVICE_MANAGEMENT_CANT_BE_USED_WITH_LEA_CONNECTION: return "PAIRING_DEVICE_MANAGEMENT_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::SOUND_AR_CANT_BE_USED_WITH_LEA_CONNECTION: return "SOUND_AR_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::AUTO_PLAY_CANT_BE_USED_WITH_LEA_CONNECTION: return "AUTO_PLAY_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::GATT_CONNECTABLE_CANT_BE_USED_WITH_LEA_CONNECTION: return "GATT_CONNECTABLE_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::SOUND_AR_OPTIMIZATION_CANT_BE_USED_WITH_LEA_CONNECTION: return "SOUND_AR_OPTIMIZATION_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::QUICK_ACCESS_CANT_BE_USED_WITH_LEA_CONNECTION: return "QUICK_ACCESS_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::CONNECTION_MODE_CANT_BE_USED_WITH_LEA_CONNECTION: return "CONNECTION_MODE_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::VOICE_ASSISTANT_SETTINGS_CANT_BE_USED_WITH_LEA_CONNECTION: return "VOICE_ASSISTANT_SETTINGS_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::VOICE_ASSISTANT_WAKE_WORD_CANT_BE_USED_WITH_LEA_CONNECTION: return "VOICE_ASSISTANT_WAKE_WORD_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::PRESET_EQ: return "PRESET_EQ";
	case MessageMdrV2FunctionType_Table1::EBB: return "EBB";
	case MessageMdrV2FunctionType_Table1::PRESET_EQ_NON_CUSTOMIZABLE: return "PRESET_EQ_NON_CUSTOMIZABLE";
	case MessageMdrV2FunctionType_Table1::PRESET_EQ_AND_ULT_MODE: return "PRESET_EQ_AND_ULT_MODE";
	case MessageMdrV2FunctionType_Table1::SOUND_EFFECT: return "SOUND_EFFECT";
	case MessageMdrV2FunctionType_Table1::CUSTOM_EQ: return "CUSTOM_EQ";
	case MessageMdrV2FunctionType_Table1::TURN_KEY_EQ: return "TURN_KEY_EQ";
	case MessageMdrV2FunctionType_Table1::PRESET_EQ_AND_ERRORCODE: return "PRESET_EQ_AND_ERRORCODE";
	case MessageMdrV2FunctionType_Table1::NOISE_CANCELLING_ONOFF: return "NOISE_CANCELLING_ONOFF";
	case MessageMdrV2FunctionType_Table1::NOISE_CANCELLING_ONOFF_AND_AMBIENT_SOUND_MODE_ONOFF: return "NOISE_CANCELLING_ONOFF_AND_AMBIENT_SOUND_MODE_ONOFF";
	case MessageMdrV2FunctionType_Table1::NOISE_CANCELLING_DUAL_SINGLE_OFF_AND_AMBIENT_SOUND_MODE_ONOFF: return "NOISE_CANCELLING_DUAL_SINGLE_OFF_AND_AMBIENT_SOUND_MODE_ONOFF";
	case MessageMdrV2FunctionType_Table1::NOISE_CANCELLING_ONOFF_AND_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT: return "NOISE_CANCELLING_ONOFF_AND_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT";
	case MessageMdrV2FunctionType_Table1::NOISE_CANCELLING_DUAL_SINGLE_OFF_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT: return "NOISE_CANCELLING_DUAL_SINGLE_OFF_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT";
	case MessageMdrV2FunctionType_Table1::AMBIENT_SOUND_MODE_ONOFF: return "AMBIENT_SOUND_MODE_ONOFF";
	case MessageMdrV2FunctionType_Table1::AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT: return "AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT";
	case MessageMdrV2FunctionType_Table1::MODE_NC_ASM_NOISE_CANCELLING_DUAL_AUTO_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT: return "MODE_NC_ASM_NOISE_CANCELLING_DUAL_AUTO_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT";
	case MessageMdrV2FunctionType_Table1::AMBIENT_SOUND_CONTROL_MODE_SELECT: return "AMBIENT_SOUND_CONTROL_MODE_SELECT";
	case MessageMdrV2FunctionType_Table1::MODE_NC_ASM_NOISE_CANCELLING_DUAL_SINGLE_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT: return "MODE_NC_ASM_NOISE_CANCELLING_DUAL_SINGLE_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT";
	case MessageMdrV2FunctionType_Table1::MODE_NC_ASM_NOISE_CANCELLING_DUAL_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT: return "MODE_NC_ASM_NOISE_CANCELLING_DUAL_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT";
	case MessageMdrV2FunctionType_Table1::MODE_NC_NCSS_ASM_NOISE_CANCELLING_DUAL_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT_WITH_TEST_MODE: return "MODE_NC_NCSS_ASM_NOISE_CANCELLING_DUAL_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT_WITH_TEST_MODE";
	case MessageMdrV2FunctionType_Table1::MODE_NC_ASM_NOISE_CANCELLING_DUAL_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT_NOISE_ADAPTATION: return "MODE_NC_ASM_NOISE_CANCELLING_DUAL_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT_NOISE_ADAPTATION";
	case MessageMdrV2FunctionType_Table1::AUTO_NCASM: return "AUTO_NCASM";
	case MessageMdrV2FunctionType_Table1::ADAPTIVE_CONTROL_WITH_PARAMETER_NOTIFICATION: return "ADAPTIVE_CONTROL_WITH_PARAMETER_NOTIFICATION";
	case MessageMdrV2FunctionType_Table1::NC_OPTIMIZER_PERSONAL_BAROMETRIC: return "NC_OPTIMIZER_PERSONAL_BAROMETRIC";
	case MessageMdrV2FunctionType_Table1::NC_OPTIMIZER_PERSONAL: return "NC_OPTIMIZER_PERSONAL";
	case MessageMdrV2FunctionType_Table1::NC_OPTIMIZER_BAROMETRIC: return "NC_OPTIMIZER_BAROMETRIC";
	case MessageMdrV2FunctionType_Table1::SOUND_FIELD_OPTIMIZATION: return "SOUND_FIELD_OPTIMIZATION";
	case MessageMdrV2FunctionType_Table1::TV_SOUND_BOOSTER: return "TV_SOUND_BOOSTER";
	case MessageMdrV2FunctionType_Table1::FIXED_MESSAGE: return "FIXED_MESSAGE";
	case MessageMdrV2FunctionType_Table1::VIBRATOR_ALERT_NOTIFICATION: return "VIBRATOR_ALERT_NOTIFICATION";
	case MessageMdrV2FunctionType_Table1::FIXED_MESSAGE_WITH_LR_SELECTION: return "FIXED_MESSAGE_WITH_LR_SELECTION";
	case MessageMdrV2FunctionType_Table1::VOICE_ASSISTANT_ALERT_NOTIFICATION: return "VOICE_ASSISTANT_ALERT_NOTIFICATION";
	case MessageMdrV2FunctionType_Table1::LE_AUDIO_ALERT_NOTIFICATION: return "LE_AUDIO_ALERT_NOTIFICATION";
	case MessageMdrV2FunctionType_Table1::PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT: return "PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT";
	case MessageMdrV2FunctionType_Table1::PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT_AND_MUTE: return "PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT_AND_MUTE";
	case MessageMdrV2FunctionType_Table1::PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT_AND_FUNCTION_CHANGE: return "PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT_AND_FUNCTION_CHANGE";
	case MessageMdrV2FunctionType_Table1::PLAYBACK_CONTROLLER_WITH_FUNCTION_CHANGE: return "PLAYBACK_CONTROLLER_WITH_FUNCTION_CHANGE";
	case MessageMdrV2FunctionType_Table1::SAR: return "SAR";
	case MessageMdrV2FunctionType_Table1::AUTO_PLAY: return "AUTO_PLAY";
	case MessageMdrV2FunctionType_Table1::GATT_CONNECTABLE: return "GATT_CONNECTABLE";
	case MessageMdrV2FunctionType_Table1::SAR_OPTIMIZATION_COMPASS_ACCEL_TYPE: return "SAR_OPTIMIZATION_COMPASS_ACCEL_TYPE";
	case MessageMdrV2FunctionType_Table1::HEAD_TRACKER_COMPASS_ACCEL_TYPE: return "HEAD_TRACKER_COMPASS_ACCEL_TYPE";
	case MessageMdrV2FunctionType_Table1::SAR_OPTIMIZATION_ACCEL_TYPE: return "SAR_OPTIMIZATION_ACCEL_TYPE";
	case MessageMdrV2FunctionType_Table1::HEAD_TRACKER_ACCEL_TYPE: return "HEAD_TRACKER_ACCEL_TYPE";
	case MessageMdrV2FunctionType_Table1::INTEGRATED_AUTO_PLAY: return "INTEGRATED_AUTO_PLAY";
	case MessageMdrV2FunctionType_Table1::ACTION_LOG_NOTIFIER: return "ACTION_LOG_NOTIFIER";
	case MessageMdrV2FunctionType_Table1::TIME_SERIES_OPERATIONLOG_NOTIFIER: return "TIME_SERIES_OPERATIONLOG_NOTIFIER";
	case MessageMdrV2FunctionType_Table1::SOUND_DROPOUT_NOTIFIER: return "SOUND_DROPOUT_NOTIFIER";
	case MessageMdrV2FunctionType_Table1::GENERAL_SETTING_1: return "GENERAL_SETTING_1";
	case MessageMdrV2FunctionType_Table1::GENERAL_SETTING_2: return "GENERAL_SETTING_2";
	case MessageMdrV2FunctionType_Table1::GENERAL_SETTING_3: return "GENERAL_SETTING_3";
	case MessageMdrV2FunctionType_Table1::GENERAL_SETTING_4: return "GENERAL_SETTING_4";
	case MessageMdrV2FunctionType_Table1::CONNECTION_MODE_SOUND_QUALITY_CONNECTION_QUALITY: return "CONNECTION_MODE_SOUND_QUALITY_CONNECTION_QUALITY";
	case MessageMdrV2FunctionType_Table1::UPSCALING_AUTO_OFF: return "UPSCALING_AUTO_OFF";
	case MessageMdrV2FunctionType_Table1::CONNECTION_MODE_SOUND_QUALITY_SOUND_WITH_LDAC_STATUS_QUALITY_CONNECTION_QUALITY: return "CONNECTION_MODE_SOUND_QUALITY_SOUND_WITH_LDAC_STATUS_QUALITY_CONNECTION_QUALITY";
	case MessageMdrV2FunctionType_Table1::BGM_MODE_SMALL_MIDDLE_LARGE: return "BGM_MODE_SMALL_MIDDLE_LARGE";
	case MessageMdrV2FunctionType_Table1::UPMIX_CINEMA: return "UPMIX_CINEMA";
	case MessageMdrV2FunctionType_Table1::LISTENING_OPTION: return "LISTENING_OPTION";
	case MessageMdrV2FunctionType_Table1::CONNECTION_MODE_CLASSIC_AUDIO_LE_AUDIO: return "CONNECTION_MODE_CLASSIC_AUDIO_LE_AUDIO";
	case MessageMdrV2FunctionType_Table1::VOICE_CONTENTS: return "VOICE_CONTENTS";
	case MessageMdrV2FunctionType_Table1::SOUND_LEAKAGE_REDUCTION: return "SOUND_LEAKAGE_REDUCTION";
	case MessageMdrV2FunctionType_Table1::LISTENING_OPTION_ASSIGN_CUSTOMIZABLE: return "LISTENING_OPTION_ASSIGN_CUSTOMIZABLE";
	case MessageMdrV2FunctionType_Table1::BGM_MODE_SMALL_MIDDLE_LARGE_AND_ERRORCODE: return "BGM_MODE_SMALL_MIDDLE_LARGE_AND_ERRORCODE";
	case MessageMdrV2FunctionType_Table1::UPMIX_SERIES: return "UPMIX_SERIES";
	case MessageMdrV2FunctionType_Table1::VIBRATOR_ON_OFF: return "VIBRATOR_ON_OFF";
	case MessageMdrV2FunctionType_Table1::PLAYBACK_CONTROL_BY_WEARING_REMOVING_HEADPHONE_ON_OFF: return "PLAYBACK_CONTROL_BY_WEARING_REMOVING_HEADPHONE_ON_OFF";
	case MessageMdrV2FunctionType_Table1::SMART_TALKING_MODE_TYPE1: return "SMART_TALKING_MODE_TYPE1";
	case MessageMdrV2FunctionType_Table1::ASSIGNABLE_SETTING: return "ASSIGNABLE_SETTING";
	case MessageMdrV2FunctionType_Table1::VOICE_ASSISTANT_SETTINGS: return "VOICE_ASSISTANT_SETTINGS";
	case MessageMdrV2FunctionType_Table1::VOICE_ASSISTANT_WAKE_WORD_ON_OFF: return "VOICE_ASSISTANT_WAKE_WORD_ON_OFF";
	case MessageMdrV2FunctionType_Table1::WEARING_STATUS_DETECTOR: return "WEARING_STATUS_DETECTOR";
	case MessageMdrV2FunctionType_Table1::EARPIECE_SELECTION: return "EARPIECE_SELECTION";
	case MessageMdrV2FunctionType_Table1::CALL_SETTINGS: return "CALL_SETTINGS";
	case MessageMdrV2FunctionType_Table1::RESET_SETTINGS: return "RESET_SETTINGS";
	case MessageMdrV2FunctionType_Table1::AUTO_VOLUME: return "AUTO_VOLUME";
	case MessageMdrV2FunctionType_Table1::FACE_TAP_TEST_MODE: return "FACE_TAP_TEST_MODE";
	case MessageMdrV2FunctionType_Table1::SMART_TALKING_MODE_TYPE2: return "SMART_TALKING_MODE_TYPE2";
	case MessageMdrV2FunctionType_Table1::QUICK_ACCESS: return "QUICK_ACCESS";
	case MessageMdrV2FunctionType_Table1::ASSIGNABLE_SETTING_WITH_LIMITATION: return "ASSIGNABLE_SETTING_WITH_LIMITATION";
	case MessageMdrV2FunctionType_Table1::HEAD_GESTURE_ON_OFF_TRAINING: return "HEAD_GESTURE_ON_OFF_TRAINING";
	default: return nullptr;
	}
}

enum class MessageMdrV2FunctionType_Table2 : UInt8
{
	AUTO_STANDBY = 0x20,
	CHARGE_IN_USE = 0x21,
	CARING_CHARGE_WITH_THRESHOLD = 0x22,
	USB_SUBMERSION = 0x23,
	PAIRING_DEVICE_MANAGEMENT_CLASSIC_BT = 0x30,
	SOURCE_SWITCH_CONTROL = 0x31,
	PAIRING_DEVICE_MANAGEMENT_WITH_BLUETOOTH_CLASS_OF_DEVICE_CLASSIC_BT = 0x32,
	PAIRING_DEVICE_MANAGEMENT_WITH_BLUETOOTH_CLASS_OF_DEVICE_CLASSIC_LE = 0x33,
	MUSIC_HAND_OVER_SETTING = 0x34,
	VOICE_GUIDANCE_SETTING_MTK_TRANSFER_WITHOUT_DISCONNECTION_NOT_SUPPORT_LANGUAGE_SWITCH = 0x40,
	VOICE_GUIDANCE_SETTING_MTK_TRANSFER_WITHOUT_DISCONNECTION_SUPPORT_LANGUAGE_SWITCH = 0x41,
	VOICE_GUIDANCE_SETTING_MTK_TRANSFER_WITHOUT_DISCONNECTION_SUPPORT_LANGUAGE_SWITCH_AND_VOLUME_ADJUSTMENT = 0x42,
	VOICE_GUIDANCE_VOLUME_SETTING_MTK_FIXED_TO_5_STEPS = 0x43,
	VOICE_GUIDANCE_SETTING_SUPPORT_LANGUAGE_SWITCH = 0x44,
	VOICE_GUIDANCE_SETTING_ONLY_ON_OFF_SWITCH = 0x45,
	VOICE_GUIDANCE_BATTERY_LEVEL_VOICE = 0x46,
	VOICE_GUIDANCE_POWER_ON_OFF_SOUND = 0x47,
	VOICE_GUIDANCE_SOUND_EFFECT_ULT_BEEP_ON_OFF = 0x48,
	SAFE_LISTENING_HBS_1 = 0x50,
	SAFE_LISTENING_TWS_1 = 0x51,
	SAFE_LISTENING_HBS_2 = 0x52,
	SAFE_LISTENING_TWS_2 = 0x53,
	SAFE_VOLUME_CONTROL = 0x54,
	LE_AUDIO_CONNECTION_STATE_NOTIFICATION = 0x60,
	LE_AUDIO_SWITCH_SUPPORTED_COMPATIBILITY = 0x61,
	LE_AUDIO_CONNECTION_MODE = 0x62,
	GET_IDENTITY_RESOLVING_KEY = 0x63,
	LINK_AUTO_SWITCH_CANT_BE_USED_WITH_LEA_CONNECTION = 0x6F,
	DJ_CONTROL = 0x70,
	ILLUMINATION = 0x71,
	KARAOKE = 0x72,
	WEARING_STATUS_CHECKER = 0xF0,
	REPEAT_TAP_TRAINING_MODE = 0xF1,
	QUICK_ACCESS_EASY_SETTING = 0xF2,
	AUTO_VOLUME_OPTIMIZER = 0xF3,
	AUTO_VOLUME_WITH_LIMITATION = 0xF4,
	SONY_VOICE_ASSISTANT = 0xF5,
	WEARING_POSITION = 0xF6,
	LINK_AUTO_SWITCH_FOR_SPEAKER = 0xF7,
	LINK_AUTO_SWITCH_FOR_HEADSETS = 0xF8,
	MIC_ON_OFF_BY_HEADPHONE_OPERATION = 0xF9,
	FUNCTION_CHANGE = 0xFA,
	USB_BROWSER = 0xFB,
	LIGHTING_MODE = 0xFC,
};

inline const char* format_as(MessageMdrV2FunctionType_Table2 func)
{
	switch (func)
	{
	case MessageMdrV2FunctionType_Table2::AUTO_STANDBY: return "AUTO_STANDBY";
    case MessageMdrV2FunctionType_Table2::CHARGE_IN_USE: return "CHARGE_IN_USE";
    case MessageMdrV2FunctionType_Table2::CARING_CHARGE_WITH_THRESHOLD: return "CARING_CHARGE_WITH_THRESHOLD";
    case MessageMdrV2FunctionType_Table2::USB_SUBMERSION: return "USB_SUBMERSION";
    case MessageMdrV2FunctionType_Table2::PAIRING_DEVICE_MANAGEMENT_CLASSIC_BT: return "PAIRING_DEVICE_MANAGEMENT_CLASSIC_BT";
    case MessageMdrV2FunctionType_Table2::SOURCE_SWITCH_CONTROL: return "SOURCE_SWITCH_CONTROL";
    case MessageMdrV2FunctionType_Table2::PAIRING_DEVICE_MANAGEMENT_WITH_BLUETOOTH_CLASS_OF_DEVICE_CLASSIC_BT: return "PAIRING_DEVICE_MANAGEMENT_WITH_BLUETOOTH_CLASS_OF_DEVICE_CLASSIC_BT";
    case MessageMdrV2FunctionType_Table2::PAIRING_DEVICE_MANAGEMENT_WITH_BLUETOOTH_CLASS_OF_DEVICE_CLASSIC_LE: return "PAIRING_DEVICE_MANAGEMENT_WITH_BLUETOOTH_CLASS_OF_DEVICE_CLASSIC_LE";
    case MessageMdrV2FunctionType_Table2::MUSIC_HAND_OVER_SETTING: return "MUSIC_HAND_OVER_SETTING";
    case MessageMdrV2FunctionType_Table2::VOICE_GUIDANCE_SETTING_MTK_TRANSFER_WITHOUT_DISCONNECTION_NOT_SUPPORT_LANGUAGE_SWITCH: return "VOICE_GUIDANCE_SETTING_MTK_TRANSFER_WITHOUT_DISCONNECTION_NOT_SUPPORT_LANGUAGE_SWITCH";
    case MessageMdrV2FunctionType_Table2::VOICE_GUIDANCE_SETTING_MTK_TRANSFER_WITHOUT_DISCONNECTION_SUPPORT_LANGUAGE_SWITCH: return "VOICE_GUIDANCE_SETTING_MTK_TRANSFER_WITHOUT_DISCONNECTION_SUPPORT_LANGUAGE_SWITCH";
    case MessageMdrV2FunctionType_Table2::VOICE_GUIDANCE_SETTING_MTK_TRANSFER_WITHOUT_DISCONNECTION_SUPPORT_LANGUAGE_SWITCH_AND_VOLUME_ADJUSTMENT: return "VOICE_GUIDANCE_SETTING_MTK_TRANSFER_WITHOUT_DISCONNECTION_SUPPORT_LANGUAGE_SWITCH_AND_VOLUME_ADJUSTMENT";
    case MessageMdrV2FunctionType_Table2::VOICE_GUIDANCE_VOLUME_SETTING_MTK_FIXED_TO_5_STEPS: return "VOICE_GUIDANCE_VOLUME_SETTING_MTK_FIXED_TO_5_STEPS";
    case MessageMdrV2FunctionType_Table2::VOICE_GUIDANCE_SETTING_SUPPORT_LANGUAGE_SWITCH: return "VOICE_GUIDANCE_SETTING_SUPPORT_LANGUAGE_SWITCH";
    case MessageMdrV2FunctionType_Table2::VOICE_GUIDANCE_SETTING_ONLY_ON_OFF_SWITCH: return "VOICE_GUIDANCE_SETTING_ONLY_ON_OFF_SWITCH";
    case MessageMdrV2FunctionType_Table2::VOICE_GUIDANCE_BATTERY_LEVEL_VOICE: return "VOICE_GUIDANCE_BATTERY_LEVEL_VOICE";
    case MessageMdrV2FunctionType_Table2::VOICE_GUIDANCE_POWER_ON_OFF_SOUND: return "VOICE_GUIDANCE_POWER_ON_OFF_SOUND";
    case MessageMdrV2FunctionType_Table2::VOICE_GUIDANCE_SOUND_EFFECT_ULT_BEEP_ON_OFF: return "VOICE_GUIDANCE_SOUND_EFFECT_ULT_BEEP_ON_OFF";
    case MessageMdrV2FunctionType_Table2::SAFE_LISTENING_HBS_1: return "SAFE_LISTENING_HBS_1";
    case MessageMdrV2FunctionType_Table2::SAFE_LISTENING_TWS_1: return "SAFE_LISTENING_TWS_1";
    case MessageMdrV2FunctionType_Table2::SAFE_LISTENING_HBS_2: return "SAFE_LISTENING_HBS_2";
    case MessageMdrV2FunctionType_Table2::SAFE_LISTENING_TWS_2: return "SAFE_LISTENING_TWS_2";
    case MessageMdrV2FunctionType_Table2::SAFE_VOLUME_CONTROL: return "SAFE_VOLUME_CONTROL";
    case MessageMdrV2FunctionType_Table2::LE_AUDIO_CONNECTION_STATE_NOTIFICATION: return "LE_AUDIO_CONNECTION_STATE_NOTIFICATION";
    case MessageMdrV2FunctionType_Table2::LE_AUDIO_SWITCH_SUPPORTED_COMPATIBILITY: return "LE_AUDIO_SWITCH_SUPPORTED_COMPATIBILITY";
    case MessageMdrV2FunctionType_Table2::LE_AUDIO_CONNECTION_MODE: return "LE_AUDIO_CONNECTION_MODE";
    case MessageMdrV2FunctionType_Table2::GET_IDENTITY_RESOLVING_KEY: return "GET_IDENTITY_RESOLVING_KEY";
    case MessageMdrV2FunctionType_Table2::LINK_AUTO_SWITCH_CANT_BE_USED_WITH_LEA_CONNECTION: return "LINK_AUTO_SWITCH_CANT_BE_USED_WITH_LEA_CONNECTION";
    case MessageMdrV2FunctionType_Table2::DJ_CONTROL: return "DJ_CONTROL";
    case MessageMdrV2FunctionType_Table2::ILLUMINATION: return "ILLUMINATION";
    case MessageMdrV2FunctionType_Table2::KARAOKE: return "KARAOKE";
    case MessageMdrV2FunctionType_Table2::WEARING_STATUS_CHECKER: return "WEARING_STATUS_CHECKER";
    case MessageMdrV2FunctionType_Table2::REPEAT_TAP_TRAINING_MODE: return "REPEAT_TAP_TRAINING_MODE";
    case MessageMdrV2FunctionType_Table2::QUICK_ACCESS_EASY_SETTING: return "QUICK_ACCESS_EASY_SETTING";
    case MessageMdrV2FunctionType_Table2::AUTO_VOLUME_OPTIMIZER: return "AUTO_VOLUME_OPTIMIZER";
    case MessageMdrV2FunctionType_Table2::AUTO_VOLUME_WITH_LIMITATION: return "AUTO_VOLUME_WITH_LIMITATION";
    case MessageMdrV2FunctionType_Table2::SONY_VOICE_ASSISTANT: return "SONY_VOICE_ASSISTANT";
    case MessageMdrV2FunctionType_Table2::WEARING_POSITION: return "WEARING_POSITION";
    case MessageMdrV2FunctionType_Table2::LINK_AUTO_SWITCH_FOR_SPEAKER: return "LINK_AUTO_SWITCH_FOR_SPEAKER";
    case MessageMdrV2FunctionType_Table2::LINK_AUTO_SWITCH_FOR_HEADSETS: return "LINK_AUTO_SWITCH_FOR_HEADSETS";
    case MessageMdrV2FunctionType_Table2::MIC_ON_OFF_BY_HEADPHONE_OPERATION: return "MIC_ON_OFF_BY_HEADPHONE_OPERATION";
    case MessageMdrV2FunctionType_Table2::FUNCTION_CHANGE: return "FUNCTION_CHANGE";
    case MessageMdrV2FunctionType_Table2::USB_BROWSER: return "USB_BROWSER";
    case MessageMdrV2FunctionType_Table2::LIGHTING_MODE: return "LIGHTING_MODE";
    default: return nullptr;
    }
}

struct MessageMdrV2SupportFunction
{
    union
    {
        MessageMdrV2FunctionType_Table1 table1;
        MessageMdrV2FunctionType_Table2 table2;
    };
    uint8_t priority;
};
}