#pragma once

#include <vector>
#include <ranges>
#include <cstdint>

#define HEADPHONES_DEFINE_ENUM_FLAG_OPERATORS(ENUMTYPE) \
extern "C++" { \
inline constexpr ENUMTYPE operator | (ENUMTYPE a, ENUMTYPE b) noexcept { return ENUMTYPE(((std::underlying_type_t<ENUMTYPE>)a) | ((std::underlying_type_t<ENUMTYPE>)b)); } \
inline ENUMTYPE &operator |= (ENUMTYPE &a, ENUMTYPE b) noexcept { return (ENUMTYPE &)(((std::underlying_type_t<ENUMTYPE> &)a) |= ((std::underlying_type_t<ENUMTYPE>)b)); } \
inline constexpr ENUMTYPE operator & (ENUMTYPE a, ENUMTYPE b) noexcept { return ENUMTYPE(((std::underlying_type_t<ENUMTYPE>)a) & ((std::underlying_type_t<ENUMTYPE>)b)); } \
inline ENUMTYPE &operator &= (ENUMTYPE &a, ENUMTYPE b) noexcept { return (ENUMTYPE &)(((std::underlying_type_t<ENUMTYPE> &)a) &= ((std::underlying_type_t<ENUMTYPE>)b)); } \
inline constexpr ENUMTYPE operator ~ (ENUMTYPE a) noexcept { return ENUMTYPE(~((std::underlying_type_t<ENUMTYPE>)a)); } \
inline constexpr ENUMTYPE operator ^ (ENUMTYPE a, ENUMTYPE b) noexcept { return ENUMTYPE(((std::underlying_type_t<ENUMTYPE>)a) ^ ((std::underlying_type_t<ENUMTYPE>)b)); } \
inline ENUMTYPE &operator ^= (ENUMTYPE &a, ENUMTYPE b) noexcept { return (ENUMTYPE &)(((std::underlying_type_t<ENUMTYPE> &)a) ^= ((std::underlying_type_t<ENUMTYPE>)b)); } \
}

inline constexpr auto MAX_BLUETOOTH_MESSAGE_SIZE = 2048;
inline constexpr char START_MARKER{ 62 };
inline constexpr char END_MARKER{ 60 };

inline constexpr auto MAC_ADDR_STR_SIZE = 17;

/*
from `spdtool browse [device mac]`

Service Name: Serial HPC
Service RecHandle: 0x20000000
Service Class ID List:
  UUID 128: 956c7b26-d49a-4ba8-b03f-b17d393cb6e2
Protocol Descriptor List:
  "L2CAP" (0x0100)
  "RFCOMM" (0x0003)
	Channel: 9
Language Base Attr List:
  code_ISO639: 0x656e
  encoding:    0x6a
  base_offset: 0x100
Profile Descriptor List:
  "Serial Port" (0x1101)
	Version: 0x0102
 */

inline constexpr auto SERVICE_UUID = "956C7B26-D49A-4BA8-B03F-B17D393CB6E2";
inline uint8_t SERVICE_UUID_IN_BYTES[] = { // this is the SERVICE_UUID but in bytes
		0x95, 0x6C, 0x7B, 0x26, 0xD4, 0x9A, 0x4B, 0xA8, 0xB0, 0x3F, 0xB1, 0x7D, 0x39, 0x3C, 0xB6, 0xE2
};

#define APP_NAME "Sony Headphones Client v" __HEADPHONES_APP_VERSION__
#define APP_NAME_W (L"" APP_NAME)
#define APP_CONFIG_ENV_KEY "SONYHEADPHONESCLIENT_CONFIG_PATH"
#define APP_CONFIG_NAME "sonyheadphonesclient.toml"
using Buffer = std::vector<uint8_t>;

enum class DATA_TYPE : uint8_t
{
	DATA = 0,
	ACK = 1,
	DATA_MC_NO1 = 2,
	DATA_ICD = 9,
	DATA_EV = 10,
	DATA_MDR = 12,
	DATA_COMMON = 13,
	DATA_MDR_NO2 = 14,
	SHOT =  16,
	SHOT_MC_NO1 =  18,
	SHOT_ICD =  25,
	SHOT_EV =  26,
	SHOT_MDR =  28,
	SHOT_COMMON =  29,
	SHOT_MDR_NO2 = 30,
	LARGE_DATA_COMMON =  45,
	UNKNOWN = 0xff
};

enum class THMSGV2T1ConnectInquiredType : uint8_t
{
	FIXED_VALUE = 0,
};

enum class THMSGV2T2ConnectInquiredType : uint8_t
{
	FIXED_VALUE = 0,
};

// CONNECT_*_DEVICE_INFO

enum class THMSGV2T1DeviceInfoType : uint8_t
{
	MODEL_NAME = 1,
	FW_VERSION = 2,
	SERIES_AND_COLOR_INFO = 3,
	INSTRUCTION_GUIDE = 4,
};

enum class THMSGV2T1ModelSeries : uint8_t
{
	NO_SERIES = 0,
	EXTRA_BASS = 0x10,
	ULT_POWER_SOUND = 0x11,
	HEAR = 0x20,
	PREMIUM = 0x30,
	SPORTS = 0x40,
	CASUAL = 0x50,
	LINK_BUDS = 0x60,
	NECKBAND = 0x70,
	LINKPOD = 0x80,
	GAMING = 0x90,
};

enum class ModelColor : uint8_t
{
	Default = 0,
	Black = 1,
	White = 2,
	Silver = 3,
	Red = 4,
	Blue = 5,
	Pink = 6,
	Yellow = 7,
	Green = 8,
	Gray = 9,
	Gold = 10,
	Cream = 11,
	Orange = 12,
	Brown = 13,
	Violet = 14,
};

// CONNECT_*_SUPPORT_FUNCTION
// Extracted from Sound Connect iOS 12.2.0

enum class MessageMdrV2FunctionType_Table1 : uint8_t
{
	CONCIERGE_DATA = 0x10,
	CONNECTION_STATUS = 0x11,
	CODEC_INDICATOR = 0x12,
	UPSCALING_INDICATOR = 0x13,
	BLE_SETUP = 0x14,
	TUTORIAL_CONTENTS_SELECT_ON_CONCIERGE = 0x15,
	CONNECTION_ESTABLISHED_TIME = 0x16,
	UNNECESSARY_AUTO_RECONNECTION = 0x17,
	DEVICE_SPECIAL_MODE = 0x18,
	PHONE_AND_CONNECTED_DEVICE_INFOMATION_FOR_CLASSIC = 0x19,
	TANDEM_RECONNECTION_REQUEST = 0x1A,
	DISPLAY_FW_VERSION = 0x1B,
	BATTERY_LEVEL_INDICATOR = 0x20,
	LEFT_RIGHT_BATTERY_LEVEL_INDICATOR = 0x21,
	CRADLE_BATTERY_LEVEL_INDICATOR = 0x22,
	POWER_OFF = 0x23,
	AUTO_POWER_OFF = 0x24,
	AUTO_POWER_OFF_WITH_WEARING_DETECTION = 0x25,
	POWER_SAVING_MODE_ON_OFF = 0x26,
	TANDEM_KEEP_ALIVE = 0x27,
	BATTERY_LEVEL_WITH_THRESHOLD = 0x28,
	LR_BATTERY_LEVEL_WITH_THRESHOLD = 0x29,
	CRADLE_BATTERY_LEVEL_WITH_THRESHOLD = 0x2A,
	BATTERY_SAFE_MODE = 0x2B,
	CARING_CHARGE = 0x2C,
	BT_STANDBY = 0x2D,
	STAMINA = 0x2E,
	AUTOMATIC_TOUCH_PANEL_BACKLIGHT_TURN_OFF = 0x2F,
	FW_UPDATE_MTK_TRANSFER_WITHOUT_DISCONNECTION = 0x32,
	FW_UPDATE_MTK_TRANSFER_WITHOUT_DISCONNECTION_AUTO_UPDATE = 0x34,
	FW_UPDATE_MTK_TRANSFER_WITH_REPAIR_MODE = 0x35,
	FW_UPDATE_MTK_TRANSFER_WITH_AC_CONNECTION_CHECK = 0x36,
	FW_UPDATE_TANDEM_TRANSFER_USING_COMMON_TABLE = 0x37,
	FW_UPDATE_USING_MC_APP = 0x38,
	TWS_SUPPORTS_A2DP_LEA_UNI_LEA_BROAD_WITH_CTKD = 0x40,
	HBS_SUPPORTS_A2DP_LEA_UNI_LEA_BROAD_WITH_CTKD = 0x41,
	CLASSIC_ONLY_LE_CLASSIC_SETTING = 0x42,
	TWS_SUPPORTS_LEA_UNI_LEA_BROAD = 0x43,
	CHANGE_TANDEM_CONNECTION_PROFILE_FOR_ANDROID = 0x44,
	BGM_MODE_CANT_BE_USED_WITH_LEA_CONNECTION = 0x45,
	HEAD_TRACKER_CANT_BE_USED_WITH_LEA_CONNECTION = 0x46,
	PAIRING_DEVICE_MANAGEMENT_CANT_BE_USED_WITH_LEA_CONNECTION = 0x47,
	SOUND_AR_CANT_BE_USED_WITH_LEA_CONNECTION = 0x48,
	AUTO_PLAY_CANT_BE_USED_WITH_LEA_CONNECTION = 0x49,
	GATT_CONNECTABLE_CANT_BE_USED_WITH_LEA_CONNECTION = 0x4A,
	SOUND_AR_OPTIMIZATION_CANT_BE_USED_WITH_LEA_CONNECTION = 0x4B,
	QUICK_ACCESS_CANT_BE_USED_WITH_LEA_CONNECTION = 0x4C,
	CONNECTION_MODE_CANT_BE_USED_WITH_LEA_CONNECTION = 0x4D,
	VOICE_ASSISTANT_SETTINGS_CANT_BE_USED_WITH_LEA_CONNECTION = 0x4E,
	VOICE_ASSISTANT_WAKE_WORD_CANT_BE_USED_WITH_LEA_CONNECTION = 0x4F,
	PRESET_EQ = 0x50,
	EBB = 0x51,
	PRESET_EQ_NON_CUSTOMIZABLE = 0x52,
	PRESET_EQ_AND_ULT_MODE = 0x53,
	SOUND_EFFECT = 0x54,
	CUSTOM_EQ = 0x55,
	TURN_KEY_EQ = 0x56,
	PRESET_EQ_AND_ERRORCODE = 0x57,
	NOISE_CANCELLING_ONOFF = 0x61,
	NOISE_CANCELLING_ONOFF_AND_AMBIENT_SOUND_MODE_ONOFF = 0x62,
	NOISE_CANCELLING_DUAL_SINGLE_OFF_AND_AMBIENT_SOUND_MODE_ONOFF = 0x63,
	NOISE_CANCELLING_ONOFF_AND_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT = 0x64,
	NOISE_CANCELLING_DUAL_SINGLE_OFF_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT = 0x65,
	AMBIENT_SOUND_MODE_ONOFF = 0x66,
	AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT = 0x67,
	MODE_NC_ASM_NOISE_CANCELLING_DUAL_AUTO_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT = 0x68,
	AMBIENT_SOUND_CONTROL_MODE_SELECT = 0x69,
	MODE_NC_ASM_NOISE_CANCELLING_DUAL_SINGLE_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT = 0x6A,
	MODE_NC_ASM_NOISE_CANCELLING_DUAL_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT = 0x6B,
	MODE_NC_NCSS_ASM_NOISE_CANCELLING_DUAL_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT_WITH_TEST_MODE = 0x6C,
	MODE_NC_ASM_NOISE_CANCELLING_DUAL_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT_NOISE_ADAPTATION = 0x6D,
	AUTO_NCASM = 0x70,
	ADAPTIVE_CONTROL_WITH_PARAMETER_NOTIFICATION = 0x71,
	NC_OPTIMIZER_PERSONAL_BAROMETRIC = 0x80,
	NC_OPTIMIZER_PERSONAL = 0x81,
	NC_OPTIMIZER_BAROMETRIC = 0x82,
	SOUND_FIELD_OPTIMIZATION = 0x83,
	TV_SOUND_BOOSTER = 0x84,
	FIXED_MESSAGE = 0x90,
	VIBRATOR_ALERT_NOTIFICATION = 0x91,
	FIXED_MESSAGE_WITH_LR_SELECTION = 0x92,
	VOICE_ASSISTANT_ALERT_NOTIFICATION = 0x93,
	LE_AUDIO_ALERT_NOTIFICATION = 0x94,
	PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT = 0xA1,
	PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT_AND_MUTE = 0xA2,
	PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT_AND_FUNCTION_CHANGE = 0xA3,
	PLAYBACK_CONTROLLER_WITH_FUNCTION_CHANGE = 0xA4,
	SAR = 0xB0,
	AUTO_PLAY = 0xB1,
	GATT_CONNECTABLE = 0xB2,
	SAR_OPTIMIZATION_COMPASS_ACCEL_TYPE = 0xB3,
	HEAD_TRACKER_COMPASS_ACCEL_TYPE = 0xB5,
	SAR_OPTIMIZATION_ACCEL_TYPE = 0xB6,
	HEAD_TRACKER_ACCEL_TYPE = 0xB7,
	INTEGRATED_AUTO_PLAY = 0xB8,
	ACTION_LOG_NOTIFIER = 0xC1,
	TIME_SERIES_OPERATIONLOG_NOTIFIER = 0xC2,
	SOUND_DROPOUT_NOTIFIER = 0xC3,
	GENERAL_SETTING_1 = 0xD1,
	GENERAL_SETTING_2 = 0xD2,
	GENERAL_SETTING_3 = 0xD3,
	GENERAL_SETTING_4 = 0xD4,
	CONNECTION_MODE_SOUND_QUALITY_CONNECTION_QUALITY = 0xE1,
	UPSCALING_AUTO_OFF = 0xE2,
	CONNECTION_MODE_SOUND_QUALITY_SOUND_WITH_LDAC_STATUS_QUALITY_CONNECTION_QUALITY = 0xE3,
	BGM_MODE_SMALL_MIDDLE_LARGE = 0xE4,
	UPMIX_CINEMA = 0xE5,
	LISTENING_OPTION = 0xE6,
	CONNECTION_MODE_CLASSIC_AUDIO_LE_AUDIO = 0xE7,
	VOICE_CONTENTS = 0xE8,
	SOUND_LEAKAGE_REDUCTION = 0xE9,
	LISTENING_OPTION_ASSIGN_CUSTOMIZABLE = 0xEA,
	BGM_MODE_SMALL_MIDDLE_LARGE_AND_ERRORCODE = 0xEB,
	UPMIX_SERIES = 0xEC,
	VIBRATOR_ON_OFF = 0xF0,
	PLAYBACK_CONTROL_BY_WEARING_REMOVING_HEADPHONE_ON_OFF = 0xF1,
	SMART_TALKING_MODE_TYPE1 = 0xF2,
	ASSIGNABLE_SETTING = 0xF3,
	VOICE_ASSISTANT_SETTINGS = 0xF4,
	VOICE_ASSISTANT_WAKE_WORD_ON_OFF = 0xF5,
	WEARING_STATUS_DETECTOR = 0xF6,
	EARPIECE_SELECTION = 0xF7,
	CALL_SETTINGS = 0xF8,
	RESET_SETTINGS = 0xF9,
	AUTO_VOLUME = 0xFA,
	FACE_TAP_TEST_MODE = 0xFB,
	SMART_TALKING_MODE_TYPE2 = 0xFC,
	QUICK_ACCESS = 0xFD,
	ASSIGNABLE_SETTING_WITH_LIMITATION = 0xFE,
	HEAD_GESTURE_ON_OFF_TRAINING = 0xFF,
};

inline const char* MessageMdrV2FunctionType_Table1ToString(MessageMdrV2FunctionType_Table1 func)
{
	switch (func)
	{
	case MessageMdrV2FunctionType_Table1::CONCIERGE_DATA: return "CONCIERGE_DATA";
	case MessageMdrV2FunctionType_Table1::CONNECTION_STATUS: return "CONNECTION_STATUS";
	case MessageMdrV2FunctionType_Table1::CODEC_INDICATOR: return "CODEC_INDICATOR";
	case MessageMdrV2FunctionType_Table1::UPSCALING_INDICATOR: return "UPSCALING_INDICATOR";
	case MessageMdrV2FunctionType_Table1::BLE_SETUP: return "BLE_SETUP";
	case MessageMdrV2FunctionType_Table1::TUTORIAL_CONTENTS_SELECT_ON_CONCIERGE: return "TUTORIAL_CONTENTS_SELECT_ON_CONCIERGE";
	case MessageMdrV2FunctionType_Table1::CONNECTION_ESTABLISHED_TIME: return "CONNECTION_ESTABLISHED_TIME";
	case MessageMdrV2FunctionType_Table1::UNNECESSARY_AUTO_RECONNECTION: return "UNNECESSARY_AUTO_RECONNECTION";
	case MessageMdrV2FunctionType_Table1::DEVICE_SPECIAL_MODE: return "DEVICE_SPECIAL_MODE";
	case MessageMdrV2FunctionType_Table1::PHONE_AND_CONNECTED_DEVICE_INFOMATION_FOR_CLASSIC: return "PHONE_AND_CONNECTED_DEVICE_INFOMATION_FOR_CLASSIC";
	case MessageMdrV2FunctionType_Table1::TANDEM_RECONNECTION_REQUEST: return "TANDEM_RECONNECTION_REQUEST";
	case MessageMdrV2FunctionType_Table1::DISPLAY_FW_VERSION: return "DISPLAY_FW_VERSION";
	case MessageMdrV2FunctionType_Table1::BATTERY_LEVEL_INDICATOR: return "BATTERY_LEVEL_INDICATOR";
	case MessageMdrV2FunctionType_Table1::LEFT_RIGHT_BATTERY_LEVEL_INDICATOR: return "LEFT_RIGHT_BATTERY_LEVEL_INDICATOR";
	case MessageMdrV2FunctionType_Table1::CRADLE_BATTERY_LEVEL_INDICATOR: return "CRADLE_BATTERY_LEVEL_INDICATOR";
	case MessageMdrV2FunctionType_Table1::POWER_OFF: return "POWER_OFF";
	case MessageMdrV2FunctionType_Table1::AUTO_POWER_OFF: return "AUTO_POWER_OFF";
	case MessageMdrV2FunctionType_Table1::AUTO_POWER_OFF_WITH_WEARING_DETECTION: return "AUTO_POWER_OFF_WITH_WEARING_DETECTION";
	case MessageMdrV2FunctionType_Table1::POWER_SAVING_MODE_ON_OFF: return "POWER_SAVING_MODE_ON_OFF";
	case MessageMdrV2FunctionType_Table1::TANDEM_KEEP_ALIVE: return "TANDEM_KEEP_ALIVE";
	case MessageMdrV2FunctionType_Table1::BATTERY_LEVEL_WITH_THRESHOLD: return "BATTERY_LEVEL_WITH_THRESHOLD";
	case MessageMdrV2FunctionType_Table1::LR_BATTERY_LEVEL_WITH_THRESHOLD: return "LR_BATTERY_LEVEL_WITH_THRESHOLD";
	case MessageMdrV2FunctionType_Table1::CRADLE_BATTERY_LEVEL_WITH_THRESHOLD: return "CRADLE_BATTERY_LEVEL_WITH_THRESHOLD";
	case MessageMdrV2FunctionType_Table1::BATTERY_SAFE_MODE: return "BATTERY_SAFE_MODE";
	case MessageMdrV2FunctionType_Table1::CARING_CHARGE: return "CARING_CHARGE";
	case MessageMdrV2FunctionType_Table1::BT_STANDBY: return "BT_STANDBY";
	case MessageMdrV2FunctionType_Table1::STAMINA: return "STAMINA";
	case MessageMdrV2FunctionType_Table1::AUTOMATIC_TOUCH_PANEL_BACKLIGHT_TURN_OFF: return "AUTOMATIC_TOUCH_PANEL_BACKLIGHT_TURN_OFF";
	case MessageMdrV2FunctionType_Table1::FW_UPDATE_MTK_TRANSFER_WITHOUT_DISCONNECTION: return "FW_UPDATE_MTK_TRANSFER_WITHOUT_DISCONNECTION";
	case MessageMdrV2FunctionType_Table1::FW_UPDATE_MTK_TRANSFER_WITHOUT_DISCONNECTION_AUTO_UPDATE: return "FW_UPDATE_MTK_TRANSFER_WITHOUT_DISCONNECTION_AUTO_UPDATE";
	case MessageMdrV2FunctionType_Table1::FW_UPDATE_MTK_TRANSFER_WITH_REPAIR_MODE: return "FW_UPDATE_MTK_TRANSFER_WITH_REPAIR_MODE";
	case MessageMdrV2FunctionType_Table1::FW_UPDATE_MTK_TRANSFER_WITH_AC_CONNECTION_CHECK: return "FW_UPDATE_MTK_TRANSFER_WITH_AC_CONNECTION_CHECK";
	case MessageMdrV2FunctionType_Table1::FW_UPDATE_TANDEM_TRANSFER_USING_COMMON_TABLE: return "FW_UPDATE_TANDEM_TRANSFER_USING_COMMON_TABLE";
	case MessageMdrV2FunctionType_Table1::FW_UPDATE_USING_MC_APP: return "FW_UPDATE_USING_MC_APP";
	case MessageMdrV2FunctionType_Table1::TWS_SUPPORTS_A2DP_LEA_UNI_LEA_BROAD_WITH_CTKD: return "TWS_SUPPORTS_A2DP_LEA_UNI_LEA_BROAD_WITH_CTKD";
	case MessageMdrV2FunctionType_Table1::HBS_SUPPORTS_A2DP_LEA_UNI_LEA_BROAD_WITH_CTKD: return "HBS_SUPPORTS_A2DP_LEA_UNI_LEA_BROAD_WITH_CTKD";
	case MessageMdrV2FunctionType_Table1::CLASSIC_ONLY_LE_CLASSIC_SETTING: return "CLASSIC_ONLY_LE_CLASSIC_SETTING";
	case MessageMdrV2FunctionType_Table1::TWS_SUPPORTS_LEA_UNI_LEA_BROAD: return "TWS_SUPPORTS_LEA_UNI_LEA_BROAD";
	case MessageMdrV2FunctionType_Table1::CHANGE_TANDEM_CONNECTION_PROFILE_FOR_ANDROID: return "CHANGE_TANDEM_CONNECTION_PROFILE_FOR_ANDROID";
	case MessageMdrV2FunctionType_Table1::BGM_MODE_CANT_BE_USED_WITH_LEA_CONNECTION: return "BGM_MODE_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::HEAD_TRACKER_CANT_BE_USED_WITH_LEA_CONNECTION: return "HEAD_TRACKER_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::PAIRING_DEVICE_MANAGEMENT_CANT_BE_USED_WITH_LEA_CONNECTION: return "PAIRING_DEVICE_MANAGEMENT_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::SOUND_AR_CANT_BE_USED_WITH_LEA_CONNECTION: return "SOUND_AR_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::AUTO_PLAY_CANT_BE_USED_WITH_LEA_CONNECTION: return "AUTO_PLAY_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::GATT_CONNECTABLE_CANT_BE_USED_WITH_LEA_CONNECTION: return "GATT_CONNECTABLE_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::SOUND_AR_OPTIMIZATION_CANT_BE_USED_WITH_LEA_CONNECTION: return "SOUND_AR_OPTIMIZATION_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::QUICK_ACCESS_CANT_BE_USED_WITH_LEA_CONNECTION: return "QUICK_ACCESS_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::CONNECTION_MODE_CANT_BE_USED_WITH_LEA_CONNECTION: return "CONNECTION_MODE_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::VOICE_ASSISTANT_SETTINGS_CANT_BE_USED_WITH_LEA_CONNECTION: return "VOICE_ASSISTANT_SETTINGS_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::VOICE_ASSISTANT_WAKE_WORD_CANT_BE_USED_WITH_LEA_CONNECTION: return "VOICE_ASSISTANT_WAKE_WORD_CANT_BE_USED_WITH_LEA_CONNECTION";
	case MessageMdrV2FunctionType_Table1::PRESET_EQ: return "PRESET_EQ";
	case MessageMdrV2FunctionType_Table1::EBB: return "EBB";
	case MessageMdrV2FunctionType_Table1::PRESET_EQ_NON_CUSTOMIZABLE: return "PRESET_EQ_NON_CUSTOMIZABLE";
	case MessageMdrV2FunctionType_Table1::PRESET_EQ_AND_ULT_MODE: return "PRESET_EQ_AND_ULT_MODE";
	case MessageMdrV2FunctionType_Table1::SOUND_EFFECT: return "SOUND_EFFECT";
	case MessageMdrV2FunctionType_Table1::CUSTOM_EQ: return "CUSTOM_EQ";
	case MessageMdrV2FunctionType_Table1::TURN_KEY_EQ: return "TURN_KEY_EQ";
	case MessageMdrV2FunctionType_Table1::PRESET_EQ_AND_ERRORCODE: return "PRESET_EQ_AND_ERRORCODE";
	case MessageMdrV2FunctionType_Table1::NOISE_CANCELLING_ONOFF: return "NOISE_CANCELLING_ONOFF";
	case MessageMdrV2FunctionType_Table1::NOISE_CANCELLING_ONOFF_AND_AMBIENT_SOUND_MODE_ONOFF: return "NOISE_CANCELLING_ONOFF_AND_AMBIENT_SOUND_MODE_ONOFF";
	case MessageMdrV2FunctionType_Table1::NOISE_CANCELLING_DUAL_SINGLE_OFF_AND_AMBIENT_SOUND_MODE_ONOFF: return "NOISE_CANCELLING_DUAL_SINGLE_OFF_AND_AMBIENT_SOUND_MODE_ONOFF";
	case MessageMdrV2FunctionType_Table1::NOISE_CANCELLING_ONOFF_AND_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT: return "NOISE_CANCELLING_ONOFF_AND_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT";
	case MessageMdrV2FunctionType_Table1::NOISE_CANCELLING_DUAL_SINGLE_OFF_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT: return "NOISE_CANCELLING_DUAL_SINGLE_OFF_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT";
	case MessageMdrV2FunctionType_Table1::AMBIENT_SOUND_MODE_ONOFF: return "AMBIENT_SOUND_MODE_ONOFF";
	case MessageMdrV2FunctionType_Table1::AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT: return "AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT";
	case MessageMdrV2FunctionType_Table1::MODE_NC_ASM_NOISE_CANCELLING_DUAL_AUTO_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT: return "MODE_NC_ASM_NOISE_CANCELLING_DUAL_AUTO_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT";
	case MessageMdrV2FunctionType_Table1::AMBIENT_SOUND_CONTROL_MODE_SELECT: return "AMBIENT_SOUND_CONTROL_MODE_SELECT";
	case MessageMdrV2FunctionType_Table1::MODE_NC_ASM_NOISE_CANCELLING_DUAL_SINGLE_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT: return "MODE_NC_ASM_NOISE_CANCELLING_DUAL_SINGLE_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT";
	case MessageMdrV2FunctionType_Table1::MODE_NC_ASM_NOISE_CANCELLING_DUAL_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT: return "MODE_NC_ASM_NOISE_CANCELLING_DUAL_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT";
	case MessageMdrV2FunctionType_Table1::MODE_NC_NCSS_ASM_NOISE_CANCELLING_DUAL_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT_WITH_TEST_MODE: return "MODE_NC_NCSS_ASM_NOISE_CANCELLING_DUAL_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT_WITH_TEST_MODE";
	case MessageMdrV2FunctionType_Table1::MODE_NC_ASM_NOISE_CANCELLING_DUAL_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT_NOISE_ADAPTATION: return "MODE_NC_ASM_NOISE_CANCELLING_DUAL_AMBIENT_SOUND_MODE_LEVEL_ADJUSTMENT_NOISE_ADAPTATION";
	case MessageMdrV2FunctionType_Table1::AUTO_NCASM: return "AUTO_NCASM";
	case MessageMdrV2FunctionType_Table1::ADAPTIVE_CONTROL_WITH_PARAMETER_NOTIFICATION: return "ADAPTIVE_CONTROL_WITH_PARAMETER_NOTIFICATION";
	case MessageMdrV2FunctionType_Table1::NC_OPTIMIZER_PERSONAL_BAROMETRIC: return "NC_OPTIMIZER_PERSONAL_BAROMETRIC";
	case MessageMdrV2FunctionType_Table1::NC_OPTIMIZER_PERSONAL: return "NC_OPTIMIZER_PERSONAL";
	case MessageMdrV2FunctionType_Table1::NC_OPTIMIZER_BAROMETRIC: return "NC_OPTIMIZER_BAROMETRIC";
	case MessageMdrV2FunctionType_Table1::SOUND_FIELD_OPTIMIZATION: return "SOUND_FIELD_OPTIMIZATION";
	case MessageMdrV2FunctionType_Table1::TV_SOUND_BOOSTER: return "TV_SOUND_BOOSTER";
	case MessageMdrV2FunctionType_Table1::FIXED_MESSAGE: return "FIXED_MESSAGE";
	case MessageMdrV2FunctionType_Table1::VIBRATOR_ALERT_NOTIFICATION: return "VIBRATOR_ALERT_NOTIFICATION";
	case MessageMdrV2FunctionType_Table1::FIXED_MESSAGE_WITH_LR_SELECTION: return "FIXED_MESSAGE_WITH_LR_SELECTION";
	case MessageMdrV2FunctionType_Table1::VOICE_ASSISTANT_ALERT_NOTIFICATION: return "VOICE_ASSISTANT_ALERT_NOTIFICATION";
	case MessageMdrV2FunctionType_Table1::LE_AUDIO_ALERT_NOTIFICATION: return "LE_AUDIO_ALERT_NOTIFICATION";
	case MessageMdrV2FunctionType_Table1::PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT: return "PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT";
	case MessageMdrV2FunctionType_Table1::PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT_AND_MUTE: return "PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT_AND_MUTE";
	case MessageMdrV2FunctionType_Table1::PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT_AND_FUNCTION_CHANGE: return "PLAYBACK_CONTROLLER_WITH_CALL_VOLUME_ADJUSTMENT_AND_FUNCTION_CHANGE";
	case MessageMdrV2FunctionType_Table1::PLAYBACK_CONTROLLER_WITH_FUNCTION_CHANGE: return "PLAYBACK_CONTROLLER_WITH_FUNCTION_CHANGE";
	case MessageMdrV2FunctionType_Table1::SAR: return "SAR";
	case MessageMdrV2FunctionType_Table1::AUTO_PLAY: return "AUTO_PLAY";
	case MessageMdrV2FunctionType_Table1::GATT_CONNECTABLE: return "GATT_CONNECTABLE";
	case MessageMdrV2FunctionType_Table1::SAR_OPTIMIZATION_COMPASS_ACCEL_TYPE: return "SAR_OPTIMIZATION_COMPASS_ACCEL_TYPE";
	case MessageMdrV2FunctionType_Table1::HEAD_TRACKER_COMPASS_ACCEL_TYPE: return "HEAD_TRACKER_COMPASS_ACCEL_TYPE";
	case MessageMdrV2FunctionType_Table1::SAR_OPTIMIZATION_ACCEL_TYPE: return "SAR_OPTIMIZATION_ACCEL_TYPE";
	case MessageMdrV2FunctionType_Table1::HEAD_TRACKER_ACCEL_TYPE: return "HEAD_TRACKER_ACCEL_TYPE";
	case MessageMdrV2FunctionType_Table1::INTEGRATED_AUTO_PLAY: return "INTEGRATED_AUTO_PLAY";
	case MessageMdrV2FunctionType_Table1::ACTION_LOG_NOTIFIER: return "ACTION_LOG_NOTIFIER";
	case MessageMdrV2FunctionType_Table1::TIME_SERIES_OPERATIONLOG_NOTIFIER: return "TIME_SERIES_OPERATIONLOG_NOTIFIER";
	case MessageMdrV2FunctionType_Table1::SOUND_DROPOUT_NOTIFIER: return "SOUND_DROPOUT_NOTIFIER";
	case MessageMdrV2FunctionType_Table1::GENERAL_SETTING_1: return "GENERAL_SETTING_1";
	case MessageMdrV2FunctionType_Table1::GENERAL_SETTING_2: return "GENERAL_SETTING_2";
	case MessageMdrV2FunctionType_Table1::GENERAL_SETTING_3: return "GENERAL_SETTING_3";
	case MessageMdrV2FunctionType_Table1::GENERAL_SETTING_4: return "GENERAL_SETTING_4";
	case MessageMdrV2FunctionType_Table1::CONNECTION_MODE_SOUND_QUALITY_CONNECTION_QUALITY: return "CONNECTION_MODE_SOUND_QUALITY_CONNECTION_QUALITY";
	case MessageMdrV2FunctionType_Table1::UPSCALING_AUTO_OFF: return "UPSCALING_AUTO_OFF";
	case MessageMdrV2FunctionType_Table1::CONNECTION_MODE_SOUND_QUALITY_SOUND_WITH_LDAC_STATUS_QUALITY_CONNECTION_QUALITY: return "CONNECTION_MODE_SOUND_QUALITY_SOUND_WITH_LDAC_STATUS_QUALITY_CONNECTION_QUALITY";
	case MessageMdrV2FunctionType_Table1::BGM_MODE_SMALL_MIDDLE_LARGE: return "BGM_MODE_SMALL_MIDDLE_LARGE";
	case MessageMdrV2FunctionType_Table1::UPMIX_CINEMA: return "UPMIX_CINEMA";
	case MessageMdrV2FunctionType_Table1::LISTENING_OPTION: return "LISTENING_OPTION";
	case MessageMdrV2FunctionType_Table1::CONNECTION_MODE_CLASSIC_AUDIO_LE_AUDIO: return "CONNECTION_MODE_CLASSIC_AUDIO_LE_AUDIO";
	case MessageMdrV2FunctionType_Table1::VOICE_CONTENTS: return "VOICE_CONTENTS";
	case MessageMdrV2FunctionType_Table1::SOUND_LEAKAGE_REDUCTION: return "SOUND_LEAKAGE_REDUCTION";
	case MessageMdrV2FunctionType_Table1::LISTENING_OPTION_ASSIGN_CUSTOMIZABLE: return "LISTENING_OPTION_ASSIGN_CUSTOMIZABLE";
	case MessageMdrV2FunctionType_Table1::BGM_MODE_SMALL_MIDDLE_LARGE_AND_ERRORCODE: return "BGM_MODE_SMALL_MIDDLE_LARGE_AND_ERRORCODE";
	case MessageMdrV2FunctionType_Table1::UPMIX_SERIES: return "UPMIX_SERIES";
	case MessageMdrV2FunctionType_Table1::VIBRATOR_ON_OFF: return "VIBRATOR_ON_OFF";
	case MessageMdrV2FunctionType_Table1::PLAYBACK_CONTROL_BY_WEARING_REMOVING_HEADPHONE_ON_OFF: return "PLAYBACK_CONTROL_BY_WEARING_REMOVING_HEADPHONE_ON_OFF";
	case MessageMdrV2FunctionType_Table1::SMART_TALKING_MODE_TYPE1: return "SMART_TALKING_MODE_TYPE1";
	case MessageMdrV2FunctionType_Table1::ASSIGNABLE_SETTING: return "ASSIGNABLE_SETTING";
	case MessageMdrV2FunctionType_Table1::VOICE_ASSISTANT_SETTINGS: return "VOICE_ASSISTANT_SETTINGS";
	case MessageMdrV2FunctionType_Table1::VOICE_ASSISTANT_WAKE_WORD_ON_OFF: return "VOICE_ASSISTANT_WAKE_WORD_ON_OFF";
	case MessageMdrV2FunctionType_Table1::WEARING_STATUS_DETECTOR: return "WEARING_STATUS_DETECTOR";
	case MessageMdrV2FunctionType_Table1::EARPIECE_SELECTION: return "EARPIECE_SELECTION";
	case MessageMdrV2FunctionType_Table1::CALL_SETTINGS: return "CALL_SETTINGS";
	case MessageMdrV2FunctionType_Table1::RESET_SETTINGS: return "RESET_SETTINGS";
	case MessageMdrV2FunctionType_Table1::AUTO_VOLUME: return "AUTO_VOLUME";
	case MessageMdrV2FunctionType_Table1::FACE_TAP_TEST_MODE: return "FACE_TAP_TEST_MODE";
	case MessageMdrV2FunctionType_Table1::SMART_TALKING_MODE_TYPE2: return "SMART_TALKING_MODE_TYPE2";
	case MessageMdrV2FunctionType_Table1::QUICK_ACCESS: return "QUICK_ACCESS";
	case MessageMdrV2FunctionType_Table1::ASSIGNABLE_SETTING_WITH_LIMITATION: return "ASSIGNABLE_SETTING_WITH_LIMITATION";
	case MessageMdrV2FunctionType_Table1::HEAD_GESTURE_ON_OFF_TRAINING: return "HEAD_GESTURE_ON_OFF_TRAINING";
	default: return nullptr;
	}
}

enum class MessageMdrV2FunctionType_Table2 : uint8_t
{
	AUTO_STANDBY = 0x20,
	CHARGE_IN_USE = 0x21,
	CARING_CHARGE_WITH_THRESHOLD = 0x22,
	USB_SUBMERSION = 0x23,
	PAIRING_DEVICE_MANAGEMENT_CLASSIC_BT = 0x30,
	SOURCE_SWITCH_CONTROL = 0x31,
	PAIRING_DEVICE_MANAGEMENT_WITH_BLUETOOTH_CLASS_OF_DEVICE_CLASSIC_BT = 0x32,
	PAIRING_DEVICE_MANAGEMENT_WITH_BLUETOOTH_CLASS_OF_DEVICE_CLASSIC_LE = 0x33,
	MUSIC_HAND_OVER_SETTING = 0x34,
	VOICE_GUIDANCE_SETTING_MTK_TRANSFER_WITHOUT_DISCONNECTION_NOT_SUPPORT_LANGUAGE_SWITCH = 0x40,
	VOICE_GUIDANCE_SETTING_MTK_TRANSFER_WITHOUT_DISCONNECTION_SUPPORT_LANGUAGE_SWITCH = 0x41,
	VOICE_GUIDANCE_SETTING_MTK_TRANSFER_WITHOUT_DISCONNECTION_SUPPORT_LANGUAGE_SWITCH_AND_VOLUME_ADJUSTMENT = 0x42,
	VOICE_GUIDANCE_VOLUME_SETTING_MTK_FIXED_TO_5_STEPS = 0x43,
	VOICE_GUIDANCE_SETTING_SUPPORT_LANGUAGE_SWITCH = 0x44,
	VOICE_GUIDANCE_SETTING_ONLY_ON_OFF_SWITCH = 0x45,
	VOICE_GUIDANCE_BATTERY_LEVEL_VOICE = 0x46,
	VOICE_GUIDANCE_POWER_ON_OFF_SOUND = 0x47,
	VOICE_GUIDANCE_SOUND_EFFECT_ULT_BEEP_ON_OFF = 0x48,
	SAFE_LISTENING_HBS_1 = 0x50,
	SAFE_LISTENING_TWS_1 = 0x51,
	SAFE_LISTENING_HBS_2 = 0x52,
	SAFE_LISTENING_TWS_2 = 0x53,
	SAFE_VOLUME_CONTROL = 0x54,
	LE_AUDIO_CONNECTION_STATE_NOTIFICATION = 0x60,
	LE_AUDIO_SWITCH_SUPPORTED_COMPATIBILITY = 0x61,
	LE_AUDIO_CONNECTION_MODE = 0x62,
	GET_IDENTITY_RESOLVING_KEY = 0x63,
	LINK_AUTO_SWITCH_CANT_BE_USED_WITH_LEA_CONNECTION = 0x6F,
	DJ_CONTROL = 0x70,
	ILLUMINATION = 0x71,
	KARAOKE = 0x72,
	WEARING_STATUS_CHECKER = 0xF0,
	REPEAT_TAP_TRAINING_MODE = 0xF1,
	QUICK_ACCESS_EASY_SETTING = 0xF2,
	AUTO_VOLUME_OPTIMIZER = 0xF3,
	AUTO_VOLUME_WITH_LIMITATION = 0xF4,
	SONY_VOICE_ASSISTANT = 0xF5,
	WEARING_POSITION = 0xF6,
	LINK_AUTO_SWITCH_FOR_SPEAKER = 0xF7,
	LINK_AUTO_SWITCH_FOR_HEADSETS = 0xF8,
	MIC_ON_OFF_BY_HEADPHONE_OPERATION = 0xF9,
	FUNCTION_CHANGE = 0xFA,
	USB_BROWSER = 0xFB,
	LIGHTING_MODE = 0xFC,
};

inline const char* MessageMdrV2FunctionType_Table2ToString(MessageMdrV2FunctionType_Table2 func)
{
	switch (func)
	{
	case MessageMdrV2FunctionType_Table2::AUTO_STANDBY: return "AUTO_STANDBY";
    case MessageMdrV2FunctionType_Table2::CHARGE_IN_USE: return "CHARGE_IN_USE";
    case MessageMdrV2FunctionType_Table2::CARING_CHARGE_WITH_THRESHOLD: return "CARING_CHARGE_WITH_THRESHOLD";
    case MessageMdrV2FunctionType_Table2::USB_SUBMERSION: return "USB_SUBMERSION";
    case MessageMdrV2FunctionType_Table2::PAIRING_DEVICE_MANAGEMENT_CLASSIC_BT: return "PAIRING_DEVICE_MANAGEMENT_CLASSIC_BT";
    case MessageMdrV2FunctionType_Table2::SOURCE_SWITCH_CONTROL: return "SOURCE_SWITCH_CONTROL";
    case MessageMdrV2FunctionType_Table2::PAIRING_DEVICE_MANAGEMENT_WITH_BLUETOOTH_CLASS_OF_DEVICE_CLASSIC_BT: return "PAIRING_DEVICE_MANAGEMENT_WITH_BLUETOOTH_CLASS_OF_DEVICE_CLASSIC_BT";
    case MessageMdrV2FunctionType_Table2::PAIRING_DEVICE_MANAGEMENT_WITH_BLUETOOTH_CLASS_OF_DEVICE_CLASSIC_LE: return "PAIRING_DEVICE_MANAGEMENT_WITH_BLUETOOTH_CLASS_OF_DEVICE_CLASSIC_LE";
    case MessageMdrV2FunctionType_Table2::MUSIC_HAND_OVER_SETTING: return "MUSIC_HAND_OVER_SETTING";
    case MessageMdrV2FunctionType_Table2::VOICE_GUIDANCE_SETTING_MTK_TRANSFER_WITHOUT_DISCONNECTION_NOT_SUPPORT_LANGUAGE_SWITCH: return "VOICE_GUIDANCE_SETTING_MTK_TRANSFER_WITHOUT_DISCONNECTION_NOT_SUPPORT_LANGUAGE_SWITCH";
    case MessageMdrV2FunctionType_Table2::VOICE_GUIDANCE_SETTING_MTK_TRANSFER_WITHOUT_DISCONNECTION_SUPPORT_LANGUAGE_SWITCH: return "VOICE_GUIDANCE_SETTING_MTK_TRANSFER_WITHOUT_DISCONNECTION_SUPPORT_LANGUAGE_SWITCH";
    case MessageMdrV2FunctionType_Table2::VOICE_GUIDANCE_SETTING_MTK_TRANSFER_WITHOUT_DISCONNECTION_SUPPORT_LANGUAGE_SWITCH_AND_VOLUME_ADJUSTMENT: return "VOICE_GUIDANCE_SETTING_MTK_TRANSFER_WITHOUT_DISCONNECTION_SUPPORT_LANGUAGE_SWITCH_AND_VOLUME_ADJUSTMENT";
    case MessageMdrV2FunctionType_Table2::VOICE_GUIDANCE_VOLUME_SETTING_MTK_FIXED_TO_5_STEPS: return "VOICE_GUIDANCE_VOLUME_SETTING_MTK_FIXED_TO_5_STEPS";
    case MessageMdrV2FunctionType_Table2::VOICE_GUIDANCE_SETTING_SUPPORT_LANGUAGE_SWITCH: return "VOICE_GUIDANCE_SETTING_SUPPORT_LANGUAGE_SWITCH";
    case MessageMdrV2FunctionType_Table2::VOICE_GUIDANCE_SETTING_ONLY_ON_OFF_SWITCH: return "VOICE_GUIDANCE_SETTING_ONLY_ON_OFF_SWITCH";
    case MessageMdrV2FunctionType_Table2::VOICE_GUIDANCE_BATTERY_LEVEL_VOICE: return "VOICE_GUIDANCE_BATTERY_LEVEL_VOICE";
    case MessageMdrV2FunctionType_Table2::VOICE_GUIDANCE_POWER_ON_OFF_SOUND: return "VOICE_GUIDANCE_POWER_ON_OFF_SOUND";
    case MessageMdrV2FunctionType_Table2::VOICE_GUIDANCE_SOUND_EFFECT_ULT_BEEP_ON_OFF: return "VOICE_GUIDANCE_SOUND_EFFECT_ULT_BEEP_ON_OFF";
    case MessageMdrV2FunctionType_Table2::SAFE_LISTENING_HBS_1: return "SAFE_LISTENING_HBS_1";
    case MessageMdrV2FunctionType_Table2::SAFE_LISTENING_TWS_1: return "SAFE_LISTENING_TWS_1";
    case MessageMdrV2FunctionType_Table2::SAFE_LISTENING_HBS_2: return "SAFE_LISTENING_HBS_2";
    case MessageMdrV2FunctionType_Table2::SAFE_LISTENING_TWS_2: return "SAFE_LISTENING_TWS_2";
    case MessageMdrV2FunctionType_Table2::SAFE_VOLUME_CONTROL: return "SAFE_VOLUME_CONTROL";
    case MessageMdrV2FunctionType_Table2::LE_AUDIO_CONNECTION_STATE_NOTIFICATION: return "LE_AUDIO_CONNECTION_STATE_NOTIFICATION";
    case MessageMdrV2FunctionType_Table2::LE_AUDIO_SWITCH_SUPPORTED_COMPATIBILITY: return "LE_AUDIO_SWITCH_SUPPORTED_COMPATIBILITY";
    case MessageMdrV2FunctionType_Table2::LE_AUDIO_CONNECTION_MODE: return "LE_AUDIO_CONNECTION_MODE";
    case MessageMdrV2FunctionType_Table2::GET_IDENTITY_RESOLVING_KEY: return "GET_IDENTITY_RESOLVING_KEY";
    case MessageMdrV2FunctionType_Table2::LINK_AUTO_SWITCH_CANT_BE_USED_WITH_LEA_CONNECTION: return "LINK_AUTO_SWITCH_CANT_BE_USED_WITH_LEA_CONNECTION";
    case MessageMdrV2FunctionType_Table2::DJ_CONTROL: return "DJ_CONTROL";
    case MessageMdrV2FunctionType_Table2::ILLUMINATION: return "ILLUMINATION";
    case MessageMdrV2FunctionType_Table2::KARAOKE: return "KARAOKE";
    case MessageMdrV2FunctionType_Table2::WEARING_STATUS_CHECKER: return "WEARING_STATUS_CHECKER";
    case MessageMdrV2FunctionType_Table2::REPEAT_TAP_TRAINING_MODE: return "REPEAT_TAP_TRAINING_MODE";
    case MessageMdrV2FunctionType_Table2::QUICK_ACCESS_EASY_SETTING: return "QUICK_ACCESS_EASY_SETTING";
    case MessageMdrV2FunctionType_Table2::AUTO_VOLUME_OPTIMIZER: return "AUTO_VOLUME_OPTIMIZER";
    case MessageMdrV2FunctionType_Table2::AUTO_VOLUME_WITH_LIMITATION: return "AUTO_VOLUME_WITH_LIMITATION";
    case MessageMdrV2FunctionType_Table2::SONY_VOICE_ASSISTANT: return "SONY_VOICE_ASSISTANT";
    case MessageMdrV2FunctionType_Table2::WEARING_POSITION: return "WEARING_POSITION";
    case MessageMdrV2FunctionType_Table2::LINK_AUTO_SWITCH_FOR_SPEAKER: return "LINK_AUTO_SWITCH_FOR_SPEAKER";
    case MessageMdrV2FunctionType_Table2::LINK_AUTO_SWITCH_FOR_HEADSETS: return "LINK_AUTO_SWITCH_FOR_HEADSETS";
    case MessageMdrV2FunctionType_Table2::MIC_ON_OFF_BY_HEADPHONE_OPERATION: return "MIC_ON_OFF_BY_HEADPHONE_OPERATION";
    case MessageMdrV2FunctionType_Table2::FUNCTION_CHANGE: return "FUNCTION_CHANGE";
    case MessageMdrV2FunctionType_Table2::USB_BROWSER: return "USB_BROWSER";
    case MessageMdrV2FunctionType_Table2::LIGHTING_MODE: return "LIGHTING_MODE";
    default: return nullptr;
    }
}

struct MessageMdrV2SupportFunction
{
	union
	{
		MessageMdrV2FunctionType_Table1 table1;
		MessageMdrV2FunctionType_Table2 table2;
	} functionType;
	uint8_t priority;
};

// NCASM_*_PARAM

enum class THMSGV2T1NcAsmInquiredType : uint8_t
{
	NC_ON_OFF = 0x1,
	NC_ON_OFF_AND_ASM_ON_OFF = 0x11,
	NC_MODE_SWITCH_AND_ASM_ON_OFF = 0x12,
	NC_ON_OFF_AND_ASM_SEAMLESS = 0x13,
	NC_MODE_SWITCH_AND_ASM_SEAMLESS = 0x14,
	MODE_NC_ASM_AUTO_NC_MODE_SWITCH_AND_ASM_SEAMLESS = 0x15,
	MODE_NC_ASM_DUAL_SINGLE_NC_MODE_SWITCH_AND_ASM_SEAMLESS = 0x16,
	MODE_NC_ASM_DUAL_NC_MODE_SWITCH_AND_ASM_SEAMLESS = 0x17,
	MODE_NC_NCSS_ASM_DUAL_NC_MODE_SWITCH_AND_ASM_SEAMLESS = 0x18,
	MODE_NC_ASM_DUAL_NC_MODE_SWITCH_AND_ASM_SEAMLESS_NA = 0x19,
	ASM_ON_OFF = 0x21,
	ASM_SEAMLESS = 0x22,
	NC_AMB_TOGGLE = 0x30,
	NC_TEST_MODE = 0x40,
};

enum class NC_ASM_EFFECT : uint8_t
{
	OFF = 0,
	ON = 1
};

enum class NC_ASM_SETTING_TYPE : uint8_t
{
	NOISE_CANCELLING = 0,
	AMBIENT_SOUND = 1
};

enum class ASM_ID : uint8_t
{
	NORMAL = 0,
	VOICE = 1
};

enum class AUTO_ASM_SENSITIVITY : uint8_t
{
	STANDARD = 0,
	HIGH = 1,
	LOW = 2
};

enum class NcAmbButtonMode : uint8_t
{
	NcAmbOff = 1,
	NcAmb = 2, // Default
	NcOff = 3,
	AmbOff = 4,
};

inline bool NcAmbButtonMode_FromStates(bool nc, bool amb, bool off, NcAmbButtonMode* ret)
{
	if (nc && amb && off) *ret = NcAmbButtonMode::NcAmbOff; // all enabled -> cycle through all 3 modes
	else if (nc && amb && !off) *ret = NcAmbButtonMode::NcAmb; // cycle between NC and AMB
	else if (nc && !amb && off) *ret = NcAmbButtonMode::NcOff; // cycle between NC and Off
	else if (!nc && amb && off) *ret = NcAmbButtonMode::AmbOff; // cycle between AMB and Off
	else return false;
	return true;
}

inline void NcAmbButtonMode_ToStates(NcAmbButtonMode mode, bool* nc, bool* amb, bool* off)
{
	switch (mode)
	{
		case NcAmbButtonMode::NcAmbOff:
			*nc = true;
			*amb = true;
			*off = true;
			break;
		case NcAmbButtonMode::NcAmb:
			*nc = true;
			*amb = true;
			*off = false;
			break;
		case NcAmbButtonMode::NcOff:
			*nc = true;
			*amb = false;
			*off = true;
			break;
		case NcAmbButtonMode::AmbOff:
			*nc = false;
			*amb = true;
			*off = true;
			break;
		default:
			*nc = true;
			*amb = true;
			*off = false;
			break;
	}
}

// GENERAL_SETTING_*_PARAM

enum class THMSGV2T1GsInquiredType : uint8_t
{
	GENERAL_SETTING1 = 0xD1, ///< Capture Voice During a Phone Call
	GENERAL_SETTING2 = 0xD2, ///< Multipoint
	GENERAL_SETTING3 = 0xD3, ///< Touch sensor control panel
	GENERAL_SETTING4 = 0xD4,
};

// AUDIO_*_PARAM

enum class ListeningMode
{
	Standard = 1,
	BGM = -1, // Should not be sent
	Cinema = 0,
};

enum class ListeningModeBgmDistanceMode
{
	MyRoom = 0,
	LivingRoom = 1,
	Cafe = 2,
};

// Extracted from Sound Connect iOS 11.0.1
enum class THMSGV2T1Command : uint8_t
{
	CONNECT_GET_PROTOCOL_INFO = 0x00,
	CONNECT_RET_PROTOCOL_INFO = 0x01,

	CONNECT_GET_CAPABILITY_INFO = 0x02,
	CONNECT_RET_CAPABILITY_INFO = 0x03,

	CONNECT_GET_DEVICE_INFO = 0x04,
	CONNECT_RET_DEVICE_INFO = 0x05,

	CONNECT_GET_SUPPORT_FUNCTION = 0x06,
	CONNECT_RET_SUPPORT_FUNCTION = 0x07,

	GET_TEST = 0x0F,

	COMMON_GET_CAPABILITY = 0x10,
	COMMON_RET_CAPABILITY = 0x11,

	COMMON_GET_STATUS = 0x12,
	COMMON_RET_STATUS = 0x13,
	COMMON_NTFY_STATUS = 0x15,

	COMMON_SET_PARAM = 0x18,
	COMMON_NTFY_PARAM = 0x19,

	POWER_GET_CAPABILITY = 0x20,
	POWER_RET_CAPABILITY = 0x21,

	POWER_GET_STATUS = 0x22,
	POWER_RET_STATUS = 0x23,
	POWER_SET_STATUS = 0x24,
	POWER_NTFY_STATUS = 0x25,

	POWER_GET_PARAM = 0x26,
	POWER_RET_PARAM = 0x27,
	POWER_SET_PARAM = 0x28,
	POWER_NTFY_PARAM = 0x29,

	UPDT_GET_CAPABILITY = 0x30,
	UPDT_RET_CAPABILITY = 0x31,

	UPDT_GET_STATUS = 0x32,
	UPDT_RET_STATUS = 0x33,
	UPDT_SET_STATUS = 0x34,
	UPDT_NTFY_STATUS = 0x35,

	UPDT_GET_PARAM = 0x36,
	UPDT_RET_PARAM = 0x37,
	UPDT_SET_PARAM = 0x38,
	UPDT_NTFY_PARAM = 0x39,

	LEA_GET_CAPABILITY = 0x40,
	LEA_RET_CAPABILITY = 0x41,

	LEA_GET_STATUS = 0x42,
	LEA_RET_STATUS = 0x43,
	LEA_NTFY_STATUS = 0x45,

	LEA_GET_PARAM = 0x46,
	LEA_RET_PARAM = 0x47,
	LEA_SET_PARAM = 0x48,
	LEA_NTFY_PARAM = 0x49,

	EQEBB_GET_STATUS = 0x52,
	EQEBB_RET_STATUS = 0x53,
	EQEBB_NTFY_STATUS = 0x55,

	EQEBB_GET_PARAM = 0x56,
	EQEBB_RET_PARAM = 0x57,
	EQEBB_SET_PARAM = 0x58,
	EQEBB_NTFY_PARAM = 0x59,

	EQEBB_GET_EXTENDED_INFO = 0x5A,
	EQEBB_RET_EXTENDED_INFO = 0x5B,

	NCASM_GET_CAPABILITY = 0x60,
	NCASM_RET_CAPABILITY = 0x61,

	NCASM_GET_STATUS = 0x62,
	NCASM_RET_STATUS = 0x63,
	NCASM_SET_STATUS = 0x64,
	NCASM_NTFY_STATUS = 0x65,

	NCASM_GET_PARAM = 0x66,
	NCASM_RET_PARAM = 0x67,
	NCASM_SET_PARAM = 0x68,
	NCASM_NTFY_PARAM = 0x69,

	SENSE_GET_CAPABILITY = 0x70,
	SENSE_RET_CAPABILITY = 0x71,
	SENSE_SET_STATUS = 0x74,
	SENSE_NTFY_STATUS = 0x75,
	SENSE_SET_PARAM = 0x78,
	SENSE_NTFY_PARAM = 0x79,
	SENSE_GET_EXT_INFO = 0x7A,
	SENSE_RET_EXT_INFO = 0x7B,

	OPT_GET_CAPABILITY = 0x80,
	OPT_RET_CAPABILITY = 0x81,
	OPT_GET_STATUS = 0x82,
	OPT_RET_STATUS = 0x83,
	OPT_SET_STATUS = 0x84,
	OPT_NTFY_STATUS = 0x85,
	OPT_GET_PARAM = 0x86,
	OPT_RET_PARAM = 0x87,
	OPT_SET_PARAM = 0x88,
	OPT_NTFY_PARAM = 0x89,

	ALERT_GET_CAPABILITY = 0x90,
	ALERT_RET_CAPABILITY = 0x91,

	ALERT_GET_STATUS = 0x92,
	ALERT_RET_STATUS = 0x93,
	ALERT_SET_STATUS = 0x94,
	ALERT_NTFY_STATUS = 0x95,

	ALERT_SET_PARAM = 0x98,
	ALERT_NTFY_PARAM = 0x99,

	PLAY_GET_CAPABILITY = 0xA0,
	PLAY_RET_CAPABILITY = 0xA1,

	PLAY_GET_STATUS = 0xA2,
	PLAY_RET_STATUS = 0xA3,
	PLAY_SET_STATUS = 0xA4,
	PLAY_NTFY_STATUS = 0xA5,

	PLAY_GET_PARAM = 0xA6,
	PLAY_RET_PARAM = 0xA7,
	PLAY_SET_PARAM = 0xA8,
	PLAY_NTFY_PARAM = 0xA9,

	SAR_AUTO_PLAY_GET_CAPABILITY = 0xB0,
	SAR_AUTO_PLAY_RET_CAPABILITY = 0xB1,

	SAR_AUTO_PLAY_GET_STATUS = 0xB2,
	SAR_AUTO_PLAY_RET_STATUS = 0xB3,
	SAR_AUTO_PLAY_NTFY_STATUS = 0xB5,

	SAR_AUTO_PLAY_GET_PARAM = 0xB6,
	SAR_AUTO_PLAY_RET_PARAM = 0xB7,
	SAR_AUTO_PLAY_SET_PARAM = 0xB8,
	SAR_AUTO_PLAY_NTFY_PARAM = 0xB9,

	LOG_SET_STATUS = 0xC4,
	LOG_NTFY_PARAM = 0xC9,

	GENERAL_SETTING_GET_CAPABILITY = 0xD0,
	GENERAL_SETTING_RET_CAPABILITY = 0xD1,

	GENERAL_SETTING_GET_STATUS = 0xD2,
	GENERAL_SETTING_RET_STATUS = 0xD3,
	GENERAL_SETTING_NTFY_STATUS = 0xD5,

	GENERAL_SETTING_GET_PARAM = 0xD6,
	GENERAL_SETTING_RET_PARAM = 0xD7,
	GENERAL_SETTING_SET_PARAM = 0xD8,
	GENERAL_SETTING_NTNY_PARAM = 0xD9,

	AUDIO_GET_CAPABILITY = 0xE0,
	AUDIO_RET_CAPABILITY = 0xE1,

	AUDIO_GET_STATUS = 0xE2,
	AUDIO_RET_STATUS = 0xE3,
	AUDIO_NTFY_STATUS = 0xE5,

	AUDIO_GET_PARAM = 0xE6,
	AUDIO_RET_PARAM = 0xE7,
	AUDIO_SET_PARAM = 0xE8,
	AUDIO_NTFY_PARAM = 0xE9,

	SYSTEM_GET_CAPABILITY = 0xF0,
	SYSTEM_RET_CAPABILITY = 0xF1,

	SYSTEM_GET_STATUS = 0xF2,
	SYSTEM_RET_STATUS = 0xF3,
	SYSTEM_SET_STATUS = 0xF4,
	SYSTEM_NTFY_STATUS = 0xF5,

	SYSTEM_GET_PARAM = 0xF6,
	SYSTEM_RET_PARAM = 0xF7,
	SYSTEM_SET_PARAM = 0xF8,
	SYSTEM_NTFY_PARAM = 0xF9,

	SYSTEM_GET_EXT_PARAM = 0xFA,
	SYSTEM_RET_EXT_PARAM = 0xFB,
	SYSTEM_SET_EXT_PARAM = 0xFC,
	SYSTEM_NTFY_EXT_PARAM = 0xFD,

	UNKNOWN = 0xFF
};

inline const char* THMSGV2T1Command_toString(THMSGV2T1Command cmd)
{
	switch (cmd) {
	case THMSGV2T1Command::CONNECT_GET_PROTOCOL_INFO: return "CONNECT_GET_PROTOCOL_INFO";
	case THMSGV2T1Command::CONNECT_RET_PROTOCOL_INFO: return "CONNECT_RET_PROTOCOL_INFO";
	case THMSGV2T1Command::CONNECT_GET_CAPABILITY_INFO: return "CONNECT_GET_CAPABILITY_INFO";
	case THMSGV2T1Command::CONNECT_RET_CAPABILITY_INFO: return "CONNECT_RET_CAPABILITY_INFO";
	case THMSGV2T1Command::CONNECT_GET_DEVICE_INFO: return "CONNECT_GET_DEVICE_INFO";
	case THMSGV2T1Command::CONNECT_RET_DEVICE_INFO: return "CONNECT_RET_DEVICE_INFO";
	case THMSGV2T1Command::CONNECT_GET_SUPPORT_FUNCTION: return "CONNECT_GET_SUPPORT_FUNCTION";
	case THMSGV2T1Command::CONNECT_RET_SUPPORT_FUNCTION: return "CONNECT_RET_SUPPORT_FUNCTION";
	case THMSGV2T1Command::GET_TEST: return "GET_TEST";
	case THMSGV2T1Command::COMMON_GET_CAPABILITY: return "COMMON_GET_CAPABILITY";
	case THMSGV2T1Command::COMMON_RET_CAPABILITY: return "COMMON_RET_CAPABILITY";
	case THMSGV2T1Command::COMMON_GET_STATUS: return "COMMON_GET_STATUS";
	case THMSGV2T1Command::COMMON_RET_STATUS: return "COMMON_RET_STATUS";
	case THMSGV2T1Command::COMMON_NTFY_STATUS: return "COMMON_NTFY_STATUS";
	case THMSGV2T1Command::COMMON_SET_PARAM: return "COMMON_SET_PARAM";
	case THMSGV2T1Command::COMMON_NTFY_PARAM: return "COMMON_NTFY_PARAM";
	case THMSGV2T1Command::POWER_GET_CAPABILITY: return "POWER_GET_CAPABILITY";
	case THMSGV2T1Command::POWER_RET_CAPABILITY: return "POWER_RET_CAPABILITY";
	case THMSGV2T1Command::POWER_GET_STATUS: return "POWER_GET_STATUS";
	case THMSGV2T1Command::POWER_RET_STATUS: return "POWER_RET_STATUS";
	case THMSGV2T1Command::POWER_SET_STATUS: return "POWER_SET_STATUS";
	case THMSGV2T1Command::POWER_NTFY_STATUS: return "POWER_NTFY_STATUS";
	case THMSGV2T1Command::POWER_GET_PARAM: return "POWER_GET_PARAM";
	case THMSGV2T1Command::POWER_RET_PARAM: return "POWER_RET_PARAM";
	case THMSGV2T1Command::POWER_SET_PARAM: return "POWER_SET_PARAM";
	case THMSGV2T1Command::POWER_NTFY_PARAM: return "POWER_NTFY_PARAM";
	case THMSGV2T1Command::UPDT_GET_CAPABILITY: return "UPDT_GET_CAPABILITY";
	case THMSGV2T1Command::UPDT_RET_CAPABILITY: return "UPDT_RET_CAPABILITY";
	case THMSGV2T1Command::UPDT_GET_STATUS: return "UPDT_GET_STATUS";
	case THMSGV2T1Command::UPDT_RET_STATUS: return "UPDT_RET_STATUS";
	case THMSGV2T1Command::UPDT_SET_STATUS: return "UPDT_SET_STATUS";
	case THMSGV2T1Command::UPDT_NTFY_STATUS: return "UPDT_NTFY_STATUS";
	case THMSGV2T1Command::UPDT_GET_PARAM: return "UPDT_GET_PARAM";
	case THMSGV2T1Command::UPDT_RET_PARAM: return "UPDT_RET_PARAM";
	case THMSGV2T1Command::UPDT_SET_PARAM: return "UPDT_SET_PARAM";
	case THMSGV2T1Command::UPDT_NTFY_PARAM: return "UPDT_NTFY_PARAM";
	case THMSGV2T1Command::LEA_GET_CAPABILITY: return "LEA_GET_CAPABILITY";
	case THMSGV2T1Command::LEA_RET_CAPABILITY: return "LEA_RET_CAPABILITY";
	case THMSGV2T1Command::LEA_GET_STATUS: return "LEA_GET_STATUS";
	case THMSGV2T1Command::LEA_RET_STATUS: return "LEA_RET_STATUS";
	case THMSGV2T1Command::LEA_NTFY_STATUS: return "LEA_NTFY_STATUS";
	case THMSGV2T1Command::LEA_GET_PARAM: return "LEA_GET_PARAM";
	case THMSGV2T1Command::LEA_RET_PARAM: return "LEA_RET_PARAM";
	case THMSGV2T1Command::LEA_SET_PARAM: return "LEA_SET_PARAM";
	case THMSGV2T1Command::LEA_NTFY_PARAM: return "LEA_NTFY_PARAM";
	case THMSGV2T1Command::EQEBB_GET_STATUS: return "EQEBB_GET_STATUS";
	case THMSGV2T1Command::EQEBB_RET_STATUS: return "EQEBB_RET_STATUS";
	case THMSGV2T1Command::EQEBB_NTFY_STATUS: return "EQEBB_NTFY_STATUS";
	case THMSGV2T1Command::EQEBB_GET_PARAM: return "EQEBB_GET_PARAM";
	case THMSGV2T1Command::EQEBB_RET_PARAM: return "EQEBB_RET_PARAM";
	case THMSGV2T1Command::EQEBB_SET_PARAM: return "EQEBB_SET_PARAM";
	case THMSGV2T1Command::EQEBB_NTFY_PARAM: return "EQEBB_NTFY_PARAM";
	case THMSGV2T1Command::EQEBB_GET_EXTENDED_INFO: return "EQEBB_GET_EXTENDED_INFO";
	case THMSGV2T1Command::EQEBB_RET_EXTENDED_INFO: return "EQEBB_RET_EXTENDED_INFO";
	case THMSGV2T1Command::NCASM_GET_CAPABILITY: return "NCASM_GET_CAPABILITY";
	case THMSGV2T1Command::NCASM_RET_CAPABILITY: return "NCASM_RET_CAPABILITY";
	case THMSGV2T1Command::NCASM_GET_STATUS: return "NCASM_GET_STATUS";
	case THMSGV2T1Command::NCASM_RET_STATUS: return "NCASM_RET_STATUS";
	case THMSGV2T1Command::NCASM_SET_STATUS: return "NCASM_SET_STATUS";
	case THMSGV2T1Command::NCASM_NTFY_STATUS: return "NCASM_NTFY_STATUS";
	case THMSGV2T1Command::NCASM_GET_PARAM: return "NCASM_GET_PARAM";
	case THMSGV2T1Command::NCASM_RET_PARAM: return "NCASM_RET_PARAM";
	case THMSGV2T1Command::NCASM_SET_PARAM: return "NCASM_SET_PARAM";
	case THMSGV2T1Command::NCASM_NTFY_PARAM: return "NCASM_NTFY_PARAM";
	case THMSGV2T1Command::SENSE_GET_CAPABILITY: return "SENSE_GET_CAPABILITY";
	case THMSGV2T1Command::SENSE_RET_CAPABILITY: return "SENSE_RET_CAPABILITY";
	case THMSGV2T1Command::SENSE_SET_STATUS: return "SENSE_SET_STATUS";
	case THMSGV2T1Command::SENSE_NTFY_STATUS: return "SENSE_NTFY_STATUS";
	case THMSGV2T1Command::SENSE_SET_PARAM: return "SENSE_SET_PARAM";
	case THMSGV2T1Command::SENSE_NTFY_PARAM: return "SENSE_NTFY_PARAM";
	case THMSGV2T1Command::SENSE_GET_EXT_INFO: return "SENSE_GET_EXT_INFO";
	case THMSGV2T1Command::SENSE_RET_EXT_INFO: return "SENSE_RET_EXT_INFO";
	case THMSGV2T1Command::OPT_GET_CAPABILITY: return "OPT_GET_CAPABILITY";
	case THMSGV2T1Command::OPT_RET_CAPABILITY: return "OPT_RET_CAPABILITY";
	case THMSGV2T1Command::OPT_GET_STATUS: return "OPT_GET_STATUS";
	case THMSGV2T1Command::OPT_RET_STATUS: return "OPT_RET_STATUS";
	case THMSGV2T1Command::OPT_SET_STATUS: return "OPT_SET_STATUS";
	case THMSGV2T1Command::OPT_NTFY_STATUS: return "OPT_NTFY_STATUS";
	case THMSGV2T1Command::OPT_GET_PARAM: return "OPT_GET_PARAM";
	case THMSGV2T1Command::OPT_RET_PARAM: return "OPT_RET_PARAM";
	case THMSGV2T1Command::OPT_SET_PARAM: return "OPT_SET_PARAM";
	case THMSGV2T1Command::OPT_NTFY_PARAM: return "OPT_NTFY_PARAM";
	case THMSGV2T1Command::ALERT_GET_CAPABILITY: return "ALERT_GET_CAPABILITY";
	case THMSGV2T1Command::ALERT_RET_CAPABILITY: return "ALERT_RET_CAPABILITY";
	case THMSGV2T1Command::ALERT_GET_STATUS: return "ALERT_GET_STATUS";
	case THMSGV2T1Command::ALERT_RET_STATUS: return "ALERT_RET_STATUS";
	case THMSGV2T1Command::ALERT_SET_STATUS: return "ALERT_SET_STATUS";
	case THMSGV2T1Command::ALERT_NTFY_STATUS: return "ALERT_NTFY_STATUS";
	case THMSGV2T1Command::ALERT_SET_PARAM: return "ALERT_SET_PARAM";
	case THMSGV2T1Command::ALERT_NTFY_PARAM: return "ALERT_NTFY_PARAM";
	case THMSGV2T1Command::PLAY_GET_CAPABILITY: return "PLAY_GET_CAPABILITY";
	case THMSGV2T1Command::PLAY_RET_CAPABILITY: return "PLAY_RET_CAPABILITY";
	case THMSGV2T1Command::PLAY_GET_STATUS: return "PLAY_GET_STATUS";
	case THMSGV2T1Command::PLAY_RET_STATUS: return "PLAY_RET_STATUS";
	case THMSGV2T1Command::PLAY_SET_STATUS: return "PLAY_SET_STATUS";
	case THMSGV2T1Command::PLAY_NTFY_STATUS: return "PLAY_NTFY_STATUS";
	case THMSGV2T1Command::PLAY_GET_PARAM: return "PLAY_GET_PARAM";
	case THMSGV2T1Command::PLAY_RET_PARAM: return "PLAY_RET_PARAM";
	case THMSGV2T1Command::PLAY_SET_PARAM: return "PLAY_SET_PARAM";
	case THMSGV2T1Command::PLAY_NTFY_PARAM: return "PLAY_NTFY_PARAM";
	case THMSGV2T1Command::SAR_AUTO_PLAY_GET_CAPABILITY: return "SAR_AUTO_PLAY_GET_CAPABILITY";
	case THMSGV2T1Command::SAR_AUTO_PLAY_RET_CAPABILITY: return "SAR_AUTO_PLAY_RET_CAPABILITY";
	case THMSGV2T1Command::SAR_AUTO_PLAY_GET_STATUS: return "SAR_AUTO_PLAY_GET_STATUS";
	case THMSGV2T1Command::SAR_AUTO_PLAY_RET_STATUS: return "SAR_AUTO_PLAY_RET_STATUS";
	case THMSGV2T1Command::SAR_AUTO_PLAY_NTFY_STATUS: return "SAR_AUTO_PLAY_NTFY_STATUS";
	case THMSGV2T1Command::SAR_AUTO_PLAY_GET_PARAM: return "SAR_AUTO_PLAY_GET_PARAM";
	case THMSGV2T1Command::SAR_AUTO_PLAY_RET_PARAM: return "SAR_AUTO_PLAY_RET_PARAM";
	case THMSGV2T1Command::SAR_AUTO_PLAY_SET_PARAM: return "SAR_AUTO_PLAY_SET_PARAM";
	case THMSGV2T1Command::SAR_AUTO_PLAY_NTFY_PARAM: return "SAR_AUTO_PLAY_NTFY_PARAM";
	case THMSGV2T1Command::LOG_SET_STATUS: return "LOG_SET_STATUS";
	case THMSGV2T1Command::LOG_NTFY_PARAM: return "LOG_NTFY_PARAM";
	case THMSGV2T1Command::GENERAL_SETTING_GET_CAPABILITY: return "GENERAL_SETTING_GET_CAPABILITY";
	case THMSGV2T1Command::GENERAL_SETTING_RET_CAPABILITY: return "GENERAL_SETTING_RET_CAPABILITY";
	case THMSGV2T1Command::GENERAL_SETTING_GET_STATUS: return "GENERAL_SETTING_GET_STATUS";
	case THMSGV2T1Command::GENERAL_SETTING_RET_STATUS: return "GENERAL_SETTING_RET_STATUS";
	case THMSGV2T1Command::GENERAL_SETTING_NTFY_STATUS: return "GENERAL_SETTING_NTFY_STATUS";
	case THMSGV2T1Command::GENERAL_SETTING_GET_PARAM: return "GENERAL_SETTING_GET_PARAM";
	case THMSGV2T1Command::GENERAL_SETTING_RET_PARAM: return "GENERAL_SETTING_RET_PARAM";
	case THMSGV2T1Command::GENERAL_SETTING_SET_PARAM: return "GENERAL_SETTING_SET_PARAM";
	case THMSGV2T1Command::GENERAL_SETTING_NTNY_PARAM: return "GENERAL_SETTING_NTNY_PARAM";
	case THMSGV2T1Command::AUDIO_GET_CAPABILITY: return "AUDIO_GET_CAPABILITY";
	case THMSGV2T1Command::AUDIO_RET_CAPABILITY: return "AUDIO_RET_CAPABILITY";
	case THMSGV2T1Command::AUDIO_GET_STATUS: return "AUDIO_GET_STATUS";
	case THMSGV2T1Command::AUDIO_RET_STATUS: return "AUDIO_RET_STATUS";
	case THMSGV2T1Command::AUDIO_NTFY_STATUS: return "AUDIO_NTFY_STATUS";
	case THMSGV2T1Command::AUDIO_GET_PARAM: return "AUDIO_GET_PARAM";
	case THMSGV2T1Command::AUDIO_RET_PARAM: return "AUDIO_RET_PARAM";
	case THMSGV2T1Command::AUDIO_SET_PARAM: return "AUDIO_SET_PARAM";
	case THMSGV2T1Command::AUDIO_NTFY_PARAM: return "AUDIO_NTFY_PARAM";
	case THMSGV2T1Command::SYSTEM_GET_CAPABILITY: return "SYSTEM_GET_CAPABILITY";
	case THMSGV2T1Command::SYSTEM_RET_CAPABILITY: return "SYSTEM_RET_CAPABILITY";
	case THMSGV2T1Command::SYSTEM_GET_STATUS: return "SYSTEM_GET_STATUS";
	case THMSGV2T1Command::SYSTEM_RET_STATUS: return "SYSTEM_RET_STATUS";
	case THMSGV2T1Command::SYSTEM_SET_STATUS: return "SYSTEM_SET_STATUS";
	case THMSGV2T1Command::SYSTEM_NTFY_STATUS: return "SYSTEM_NTFY_STATUS";
	case THMSGV2T1Command::SYSTEM_GET_PARAM: return "SYSTEM_GET_PARAM";
	case THMSGV2T1Command::SYSTEM_RET_PARAM: return "SYSTEM_RET_PARAM";
	case THMSGV2T1Command::SYSTEM_SET_PARAM: return "SYSTEM_SET_PARAM";
	case THMSGV2T1Command::SYSTEM_NTFY_PARAM: return "SYSTEM_NTFY_PARAM";
	case THMSGV2T1Command::SYSTEM_GET_EXT_PARAM: return "SYSTEM_GET_EXT_PARAM";
	case THMSGV2T1Command::SYSTEM_RET_EXT_PARAM: return "SYSTEM_RET_EXT_PARAM";
	case THMSGV2T1Command::SYSTEM_SET_EXT_PARAM: return "SYSTEM_SET_EXT_PARAM";
	case THMSGV2T1Command::SYSTEM_NTFY_EXT_PARAM: return "SYSTEM_NTFY_EXT_PARAM";
	default: return "???";
	}
}

enum class THMSGV2T2Command : uint8_t
{
	CONNECT_GET_SUPPORT_FUNCTION = 0x06,
	CONNECT_RET_SUPPORT_FUNCTION = 0x07,
	POWER_GET_CAPABILITY = 0x20,
	POWER_RET_CAPABILITY = 0x21,
	POWER_GET_STATUS = 0x22,
	POWER_RET_STATUS = 0x23,
	POWER_SET_STATUS = 0x24,
	POWER_NTFY_STATUS = 0x25,
	POWER_GET_PARAM = 0x26,
	POWER_RET_PARAM = 0x27,
	POWER_SET_PARAM = 0x28,
	POWER_NTFY_PARAM = 0x29,
	PERI_GET_CAPABILITY = 0x30,
	PERI_RET_CAPABILITY = 0x31,
	PERI_GET_STATUS = 0x32,
	PERI_RET_STATUS = 0x33,
	PERI_SET_STATUS = 0x34,
	PERI_NTFY_STATUS = 0x35,
	PERI_GET_PARAM = 0x36,
	PERI_RET_PARAM = 0x37,
	PERI_SET_PARAM = 0x38,
	PERI_NTFY_PARAM = 0x39,
	MULTIPOINT_DEVICE_GET = 0x3A, // Not in official enum
	MULTIPOINT_DEVICE_RET = 0x3B, // Not in official enum
	PERI_SET_EXTENDED_PARAM = 0x3C,
	PERI_NTFY_EXTENDED_PARAM = 0x3D,
	VOICE_GUIDANCE_GET_CAPABILITY = 0x40,
	VOICE_GUIDANCE_RET_CAPABILITY = 0x41,
	VOICE_GUIDANCE_GET_STATUS = 0x42,
	VOICE_GUIDANCE_RET_STATUS = 0x43,
	VOICE_GUIDANCE_SET_STATUS = 0x44,
	VOICE_GUIDANCE_NTFY_STATUS = 0x45,
	VOICE_GUIDANCE_GET_PARAM = 0x46,
	VOICE_GUIDANCE_RET_PARAM = 0x47,
	VOICE_GUIDANCE_SET_PARAM = 0x48,
	VOICE_GUIDANCE_NTFY_PARAM = 0x49,
	VOICE_GUIDANCE_GET_EXTENDED_PARAM = 0x4A,
	VOICE_GUIDANCE_RET_EXTENDED_PARAM = 0x4B,
	SAFE_LISTENING_GET_CAPABILITY = 0x50,
	SAFE_LISTENING_RET_CAPABILITY = 0x51,
	SAFE_LISTENING_GET_STATUS = 0x52,
	SAFE_LISTENING_RET_STATUS = 0x53,
	SAFE_LISTENING_SET_STATUS = 0x54,
	SAFE_LISTENING_NTFY_STATUS = 0x55,
	SAFE_LISTENING_GET_PARAM = 0x56,
	SAFE_LISTENING_RET_PARAM = 0x57,
	SAFE_LISTENING_SET_PARAM = 0x58,
	SAFE_LISTENING_NTFY_PARAM = 0x59,
	SAFE_LISTENING_GET_EXTENDED_PARAM = 0x5A,
	SAFE_LISTENING_RET_EXTENDED_PARAM = 0x5B,
	LEA_GET_CAPABILITY = 0x60,
	LEA_RET_CAPABILITY = 0x61,
	LEA_GET_STATUS = 0x62,
	LEA_RET_STATUS = 0x63,
	LEA_NTFY_STATUS = 0x65,
	LEA_GET_PARAM = 0x66,
	LEA_RET_PARAM = 0x67,
	LEA_SET_PARAM = 0x68,
	LEA_NTFY_PARAM = 0x69,
	PARTY_GET_CAPABILITY = 0x70,
	PARTY_RET_CAPABILITY = 0x71,
	PARTY_GET_STATUS = 0x72,
	PARTY_RET_STATUS = 0x73,
	PARTY_SET_STATUS = 0x74,
	PARTY_NTFY_STATUS = 0x75,
	PARTY_GET_PARAM = 0x76,
	PARTY_RET_PARAM = 0x77,
	PARTY_SET_PARAM = 0x78,
	PARTY_NTFY_PARAM = 0x79,
	PARTY_SET_EXTENDED_PARAM = 0x7C,
	SYSTEM_GET_CAPABILITY = 0xF0,
	SYSTEM_RET_CAPABILITY = 0xF1,
	SYSTEM_GET_STATUS = 0xF2,
	SYSTEM_RET_STATUS = 0xF3,
	SYSTEM_SET_STATUS = 0xF4,
	SYSTEM_NTFY_STATUS = 0xF5,
	SYSTEM_GET_PARAM = 0xF6,
	SYSTEM_RET_PARAM = 0xF7,
	SYSTEM_SET_PARAM = 0xF8,
	SYSTEM_NTFY_PARAM = 0xF9,
	SYSTEM_GET_EXTENDED_PARAM = 0xFA,
	SYSTEM_RET_EXTENDED_PARAM = 0xFB,
	SYSTEM_SET_EXTENDED_PARAM = 0xFC,
	SYSTEM_NTFY_EXTENDED_PARAM = 0xFD,

	UNKNOWN = 0xFF
};

inline const char* THMSGV2T2Command_toString(THMSGV2T2Command cmd)
{
	switch (cmd) {
	case THMSGV2T2Command::CONNECT_GET_SUPPORT_FUNCTION: return "CONNECT_GET_SUPPORT_FUNCTION";
    case THMSGV2T2Command::CONNECT_RET_SUPPORT_FUNCTION: return "CONNECT_RET_SUPPORT_FUNCTION";
    case THMSGV2T2Command::POWER_GET_CAPABILITY: return "POWER_GET_CAPABILITY";
    case THMSGV2T2Command::POWER_RET_CAPABILITY: return "POWER_RET_CAPABILITY";
    case THMSGV2T2Command::POWER_GET_STATUS: return "POWER_GET_STATUS";
    case THMSGV2T2Command::POWER_RET_STATUS: return "POWER_RET_STATUS";
    case THMSGV2T2Command::POWER_SET_STATUS: return "POWER_SET_STATUS";
    case THMSGV2T2Command::POWER_NTFY_STATUS: return "POWER_NTFY_STATUS";
    case THMSGV2T2Command::POWER_GET_PARAM: return "POWER_GET_PARAM";
    case THMSGV2T2Command::POWER_RET_PARAM: return "POWER_RET_PARAM";
    case THMSGV2T2Command::POWER_SET_PARAM: return "POWER_SET_PARAM";
    case THMSGV2T2Command::POWER_NTFY_PARAM: return "POWER_NTFY_PARAM";
    case THMSGV2T2Command::PERI_GET_CAPABILITY: return "PERI_GET_CAPABILITY";
    case THMSGV2T2Command::PERI_RET_CAPABILITY: return "PERI_RET_CAPABILITY";
    case THMSGV2T2Command::PERI_GET_STATUS: return "PERI_GET_STATUS";
    case THMSGV2T2Command::PERI_RET_STATUS: return "PERI_RET_STATUS";
    case THMSGV2T2Command::PERI_SET_STATUS: return "PERI_SET_STATUS";
    case THMSGV2T2Command::PERI_NTFY_STATUS: return "PERI_NTFY_STATUS";
    case THMSGV2T2Command::PERI_GET_PARAM: return "PERI_GET_PARAM";
    case THMSGV2T2Command::PERI_RET_PARAM: return "PERI_RET_PARAM";
    case THMSGV2T2Command::PERI_SET_PARAM: return "PERI_SET_PARAM";
    case THMSGV2T2Command::PERI_NTFY_PARAM: return "PERI_NTFY_PARAM";
	case THMSGV2T2Command::MULTIPOINT_DEVICE_GET: return "MULTIPOINT_DEVICE_GET";
	case THMSGV2T2Command::MULTIPOINT_DEVICE_RET: return "MULTIPOINT_DEVICE_RET";
    case THMSGV2T2Command::PERI_SET_EXTENDED_PARAM: return "PERI_SET_EXTENDED_PARAM";
    case THMSGV2T2Command::PERI_NTFY_EXTENDED_PARAM: return "PERI_NTFY_EXTENDED_PARAM";
    case THMSGV2T2Command::VOICE_GUIDANCE_GET_CAPABILITY: return "VOICE_GUIDANCE_GET_CAPABILITY";
    case THMSGV2T2Command::VOICE_GUIDANCE_RET_CAPABILITY: return "VOICE_GUIDANCE_RET_CAPABILITY";
    case THMSGV2T2Command::VOICE_GUIDANCE_GET_STATUS: return "VOICE_GUIDANCE_GET_STATUS";
    case THMSGV2T2Command::VOICE_GUIDANCE_RET_STATUS: return "VOICE_GUIDANCE_RET_STATUS";
    case THMSGV2T2Command::VOICE_GUIDANCE_SET_STATUS: return "VOICE_GUIDANCE_SET_STATUS";
    case THMSGV2T2Command::VOICE_GUIDANCE_NTFY_STATUS: return "VOICE_GUIDANCE_NTFY_STATUS";
    case THMSGV2T2Command::VOICE_GUIDANCE_GET_PARAM: return "VOICE_GUIDANCE_GET_PARAM";
    case THMSGV2T2Command::VOICE_GUIDANCE_RET_PARAM: return "VOICE_GUIDANCE_RET_PARAM";
    case THMSGV2T2Command::VOICE_GUIDANCE_SET_PARAM: return "VOICE_GUIDANCE_SET_PARAM";
    case THMSGV2T2Command::VOICE_GUIDANCE_NTFY_PARAM: return "VOICE_GUIDANCE_NTFY_PARAM";
    case THMSGV2T2Command::VOICE_GUIDANCE_GET_EXTENDED_PARAM: return "VOICE_GUIDANCE_GET_EXTENDED_PARAM";
    case THMSGV2T2Command::VOICE_GUIDANCE_RET_EXTENDED_PARAM: return "VOICE_GUIDANCE_RET_EXTENDED_PARAM";
    case THMSGV2T2Command::SAFE_LISTENING_GET_CAPABILITY: return "SAFE_LISTENING_GET_CAPABILITY";
    case THMSGV2T2Command::SAFE_LISTENING_RET_CAPABILITY: return "SAFE_LISTENING_RET_CAPABILITY";
    case THMSGV2T2Command::SAFE_LISTENING_GET_STATUS: return "SAFE_LISTENING_GET_STATUS";
    case THMSGV2T2Command::SAFE_LISTENING_RET_STATUS: return "SAFE_LISTENING_RET_STATUS";
    case THMSGV2T2Command::SAFE_LISTENING_SET_STATUS: return "SAFE_LISTENING_SET_STATUS";
    case THMSGV2T2Command::SAFE_LISTENING_NTFY_STATUS: return "SAFE_LISTENING_NTFY_STATUS";
    case THMSGV2T2Command::SAFE_LISTENING_GET_PARAM: return "SAFE_LISTENING_GET_PARAM";
    case THMSGV2T2Command::SAFE_LISTENING_RET_PARAM: return "SAFE_LISTENING_RET_PARAM";
    case THMSGV2T2Command::SAFE_LISTENING_SET_PARAM: return "SAFE_LISTENING_SET_PARAM";
    case THMSGV2T2Command::SAFE_LISTENING_NTFY_PARAM: return "SAFE_LISTENING_NTFY_PARAM";
    case THMSGV2T2Command::SAFE_LISTENING_GET_EXTENDED_PARAM: return "SAFE_LISTENING_GET_EXTENDED_PARAM";
    case THMSGV2T2Command::SAFE_LISTENING_RET_EXTENDED_PARAM: return "SAFE_LISTENING_RET_EXTENDED_PARAM";
    case THMSGV2T2Command::LEA_GET_CAPABILITY: return "LEA_GET_CAPABILITY";
    case THMSGV2T2Command::LEA_RET_CAPABILITY: return "LEA_RET_CAPABILITY";
    case THMSGV2T2Command::LEA_GET_STATUS: return "LEA_GET_STATUS";
    case THMSGV2T2Command::LEA_RET_STATUS: return "LEA_RET_STATUS";
    case THMSGV2T2Command::LEA_NTFY_STATUS: return "LEA_NTFY_STATUS";
    case THMSGV2T2Command::LEA_GET_PARAM: return "LEA_GET_PARAM";
    case THMSGV2T2Command::LEA_RET_PARAM: return "LEA_RET_PARAM";
    case THMSGV2T2Command::LEA_SET_PARAM: return "LEA_SET_PARAM";
    case THMSGV2T2Command::LEA_NTFY_PARAM: return "LEA_NTFY_PARAM";
    case THMSGV2T2Command::PARTY_GET_CAPABILITY: return "PARTY_GET_CAPABILITY";
    case THMSGV2T2Command::PARTY_RET_CAPABILITY: return "PARTY_RET_CAPABILITY";
    case THMSGV2T2Command::PARTY_GET_STATUS: return "PARTY_GET_STATUS";
    case THMSGV2T2Command::PARTY_RET_STATUS: return "PARTY_RET_STATUS";
    case THMSGV2T2Command::PARTY_SET_STATUS: return "PARTY_SET_STATUS";
    case THMSGV2T2Command::PARTY_NTFY_STATUS: return "PARTY_NTFY_STATUS";
    case THMSGV2T2Command::PARTY_GET_PARAM: return "PARTY_GET_PARAM";
    case THMSGV2T2Command::PARTY_RET_PARAM: return "PARTY_RET_PARAM";
    case THMSGV2T2Command::PARTY_SET_PARAM: return "PARTY_SET_PARAM";
    case THMSGV2T2Command::PARTY_NTFY_PARAM: return "PARTY_NTFY_PARAM";
    case THMSGV2T2Command::PARTY_SET_EXTENDED_PARAM: return "PARTY_SET_EXTENDED_PARAM";
    case THMSGV2T2Command::SYSTEM_GET_CAPABILITY: return "SYSTEM_GET_CAPABILITY";
    case THMSGV2T2Command::SYSTEM_RET_CAPABILITY: return "SYSTEM_RET_CAPABILITY";
    case THMSGV2T2Command::SYSTEM_GET_STATUS: return "SYSTEM_GET_STATUS";
    case THMSGV2T2Command::SYSTEM_RET_STATUS: return "SYSTEM_RET_STATUS";
    case THMSGV2T2Command::SYSTEM_SET_STATUS: return "SYSTEM_SET_STATUS";
    case THMSGV2T2Command::SYSTEM_NTFY_STATUS: return "SYSTEM_NTFY_STATUS";
    case THMSGV2T2Command::SYSTEM_GET_PARAM: return "SYSTEM_GET_PARAM";
    case THMSGV2T2Command::SYSTEM_RET_PARAM: return "SYSTEM_RET_PARAM";
    case THMSGV2T2Command::SYSTEM_SET_PARAM: return "SYSTEM_SET_PARAM";
    case THMSGV2T2Command::SYSTEM_NTFY_PARAM: return "SYSTEM_NTFY_PARAM";
    case THMSGV2T2Command::SYSTEM_GET_EXTENDED_PARAM: return "SYSTEM_GET_EXTENDED_PARAM";
    case THMSGV2T2Command::SYSTEM_RET_EXTENDED_PARAM: return "SYSTEM_RET_EXTENDED_PARAM";
    case THMSGV2T2Command::SYSTEM_SET_EXTENDED_PARAM: return "SYSTEM_SET_EXTENDED_PARAM";
    case THMSGV2T2Command::SYSTEM_NTFY_EXTENDED_PARAM: return "SYSTEM_NTFY_EXTENDED_PARAM";
	default: return "???";
	}
}

enum class PLAYBACK_CONTROL : uint8_t
{
	NONE = 0,
	PAUSE = 1,
	NEXT = 2,
	PREV = 3,
	PLAY = 7
};

enum class PLAYBACK_CONTROL_RESPONSE : uint8_t
{
	PLAY = 1,
	PAUSE = 2
};

enum class TOUCH_SENSOR_FUNCTION : uint8_t
{
	PLAYBACK_CONTROL = 0x20,
	AMBIENT_NC_CONTROL = 0x35,
	NOT_ASSIGNED = 0xff,
	
	NUM_FUNCTIONS = 3
};

// https://github.com/Plutoberth/SonyHeadphonesClient/commit/66d8e52aad4ffd08aa78e811a23f67a5bad07d9a
enum class EQ_PRESET_ID: uint8_t {
	OFF = 0,
	ROCK = 1,
	POP = 2,
	JAZZ = 3,
	DANCE = 4,
	EDM = 5,
	R_AND_B_HIP_HOP = 6,
	ACOUSTIC = 7,
	/*RESERVED_FOR_FUTURE_NO8 = 8,… */
	/*RESERVED_FOR_FUTURE_NO15 = 15,*/
	BRIGHT = 16,
	EXCITED = 17,
	MELLOW = 18,
	RELAXED = 19,
	VOCAL = 20,
	TREBLE = 21,
	BASS = 22,
	SPEECH = 23,
	/*RESERVED_FOR_FUTURE_NO24 = 24,… */
	/*RESERVED_FOR_FUTURE_NO31 = 31,*/
	CUSTOM = 0xa0,
	USER_SETTING1 = 0xa1,
	USER_SETTING2 = 0xa2,
	USER_SETTING3 = 0xa3,
	USER_SETTING4 = 0xa4,
	USER_SETTING5 = 0xa5,
	UNSPECIFIED = 0xff,
};
